<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, ref, useId, watch } from 'vue';
import { t } from '../i18n';
defineOptions({inheritAttrs:false});
type Option={value:string|number;label:string;disabled?:boolean};
const props=withDefaults(defineProps<{modelValue?:string|number;options:Option[];disabled?:boolean;required?:boolean;placeholder?:string}>(),{placeholder:''});
const emit=defineEmits(['update:modelValue','change']);
const uid=useId(),trigger=ref<HTMLButtonElement>(),panel=ref<HTMLElement>(),search=ref<HTMLInputElement>(),open=ref(false),query=ref(''),index=ref(0),position=ref({});
const selected=computed(()=>props.options.find(o=>o.value===props.modelValue));
const filtered=computed(()=>props.options.filter(o=>o.label.toLocaleLowerCase().includes(query.value.toLocaleLowerCase())));
function place(){const r=trigger.value?.getBoundingClientRect();if(!r)return;const height=Math.min(320,window.innerHeight-24),below=window.innerHeight-r.bottom;position.value={left:Math.max(8,Math.min(r.left,window.innerWidth-r.width-8))+'px',width:r.width+'px',maxHeight:Math.max(100,Math.min(height,below>=180?below-8:r.top-8))+'px',top:below>=180?r.bottom+4+'px':'auto',bottom:below>=180?'auto':window.innerHeight-r.top+4+'px'};}
function close(focus=false){panel.value?.hidePopover();open.value=false;if(focus)trigger.value?.focus();}
async function show(){if(props.disabled)return;query.value='';index.value=Math.max(0,props.options.findIndex(o=>o.value===props.modelValue));place();panel.value?.showPopover();open.value=true;await nextTick();if(props.options.length>8)search.value?.focus();scrollActive();}
function choose(o:Option){if(o.disabled)return;emit('update:modelValue',o.value);emit('change',o.value);close(true);}
function scrollActive(){nextTick(()=>panel.value?.querySelector('[data-active="true"]')?.scrollIntoView({block:'nearest'}));}
function key(event:KeyboardEvent){if(event.key==='Escape'&&open.value){event.preventDefault();event.stopPropagation();close(true);return;}if(event.key==='Tab'){close();return;}if(['ArrowDown','ArrowUp','Home','End'].includes(event.key)){event.preventDefault();if(!open.value){void show();return;}const direction=event.key==='ArrowUp'?-1:1;let n=event.key==='Home'?0:event.key==='End'?filtered.value.length-1:index.value+direction;for(let tries=0;tries<filtered.value.length;tries++,n+=direction){n=(n+filtered.value.length)%filtered.value.length;if(!filtered.value[n]?.disabled){index.value=n;break;}}scrollActive();}else if(event.key==='Enter'&&open.value){event.preventDefault();event.stopPropagation();const option=filtered.value[index.value];if(option)choose(option);}}
watch(query,()=>{index.value=0;},{flush:'sync'});watch(()=>props.disabled,v=>{if(v)close();});
function onToggle(event:Event){open.value=(event as ToggleEvent).newState==='open';}
function onScroll(event:Event){if(open.value&&!panel.value?.contains(event.target as Node))close();}
window.addEventListener('resize',place);window.addEventListener('scroll',onScroll,true);
onBeforeUnmount(()=>{window.removeEventListener('resize',place);window.removeEventListener('scroll',onScroll,true);});
</script>
<template>
<span class="pos-select" :class="$attrs.class" :style="$attrs.style as any">
<button ref="trigger" v-bind="{...$attrs,class:undefined,style:undefined}" type="button" class="pos-select-trigger" role="combobox" aria-haspopup="listbox" :aria-expanded="open" :aria-controls="uid" :aria-activedescendant="open?uid+'-'+index:undefined" :aria-required="required" :disabled="disabled" @click="open?close():show()" @keydown="key"><span>{{selected?.label||placeholder||t('请选择')}}</span><span class="pos-select-arrow" :class="{open}">⌄</span></button>
<input v-if="required" class="pos-select-validation" tabindex="-1" aria-hidden="true" :value="selected&&modelValue!==''?String(modelValue):''" required :disabled="disabled" @invalid.prevent="show()" />
<div ref="panel" popover="auto" class="pos-select-panel" :style="position" @toggle="onToggle" @keydown="key">
<input v-if="options.length>8" ref="search" v-model="query" class="pos-select-search" :placeholder="t('搜索')" :aria-label="t('搜索')" role="combobox" :aria-controls="uid" :aria-expanded="open" :aria-activedescendant="uid+'-'+index" />
<div :id="uid" role="listbox" class="pos-select-options"><div v-for="(option,i) in filtered" :id="uid+'-'+i" :key="option.value" role="option" :aria-selected="option.value===modelValue" :aria-disabled="option.disabled" :data-active="i===index" class="pos-select-option" @pointermove="index=i" @mousedown.prevent @click="choose(option)"><span>{{option.label}}</span><span v-if="option.value===modelValue">✓</span></div><p v-if="!filtered.length" class="pos-select-empty">{{t('暂无匹配记录，请调整搜索条件。')}}</p></div>
</div>
</span>
</template>
<style>
.pos-select{display:inline-block;position:relative;min-width:0;width:100%;vertical-align:middle}.pos-select .pos-select-trigger{display:flex;align-items:center;justify-content:space-between;gap:12px;width:100%;min-height:36px;padding:8px 12px;border:1px solid var(--theme-line, #c5d2e2);border-radius:4px;background:var(--theme-surface, #fff);color:var(--theme-ink, #253858);text-align:left;font:inherit;cursor:pointer}.pos-select-trigger>span:first-child{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.pos-select .pos-select-trigger:hover:not(:disabled){border-color:var(--theme-line, #8da6c8);background:var(--theme-surface, #fff)}.pos-select .pos-select-trigger:focus-visible{outline:2px solid var(--theme-accent, #2856d9);outline-offset:2px}.pos-select .pos-select-trigger:disabled{background:var(--theme-surface, #f4f6f9);color:var(--theme-muted, #7b8ba2);cursor:not-allowed}.pos-select-arrow{color:var(--theme-muted, #667b99);transition:transform 160ms ease}.pos-select-arrow.open{transform:rotate(180deg)}.pos-select-panel{position:fixed;inset:auto;margin:0;padding:6px;border:1px solid var(--theme-line, #dce5f2);border-radius:4px;background:var(--theme-surface, white);color:var(--theme-ink, #253858);box-sizing:border-box;overflow:auto;font:14px/1.5 system-ui;animation:pos-select-in 160ms ease-out}.pos-select-panel .pos-select-search{position:sticky;top:0;z-index:1;width:100%;box-sizing:border-box;height:36px;margin:0 0 6px;padding:6px 10px;border:1px solid var(--theme-line, #c5d2e2);border-radius:3px;background:var(--theme-surface, #fff);color:var(--theme-ink, #253858)}.pos-select-option{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:8px 10px;scroll-margin-top:44px;cursor:pointer;border-radius:3px;overflow-wrap:anywhere}.pos-select-option[data-active=true]{background:var(--theme-raised, #f0f4fa);outline:1px solid var(--theme-text-accent,#2455dc);outline-offset:-1px}.pos-select-option[aria-selected=true]{color:var(--theme-text-accent, #2455dc);background:var(--theme-selected, #edf3ff);font-weight:600}.pos-select-option[aria-disabled=true]{opacity:.5;cursor:not-allowed}.pos-select-empty{padding:12px;color:var(--theme-muted, #60718a)}.pos-select .pos-select-validation{position:absolute;width:1px;height:1px;opacity:0;padding:0;pointer-events:none}.list-pagination .pos-select{width:108px;flex:none}.list-pagination .pos-select .pos-select-trigger{min-height:32px;height:32px;padding:4px 8px;font-size:13px}@keyframes pos-select-in{from{opacity:0}to{opacity:1}}@media(prefers-reduced-motion:reduce){.pos-select-panel{animation:none}.pos-select-arrow{transition:none}}
</style>
