// European Portuguese (pt-PT) UI copy. Business names are translated separately.
export const portuguese: Record<string, string> = {
  "变体图片": "Imagem da variante",
  "名称、分类和描述由所有变体共用。": "Todas as variantes partilham o nome, a categoria e a descrição.",
  "商品变体": "Variantes do produto",
  "添加变体": "Adicionar variante",
  "变体 {0}": "Variante {0}",
  "逐条添加实际销售的规格，条码由您录入或扫码填写。": "Adicione cada variante à venda. Introduza ou leia o respetivo código de barras.",
  "更换图片": "Alterar imagem",
  "属性": "Atributo",
  "添加属性": "Adicionar atributo",
  "移除属性": "Remover atributo",
  "例如：颜色": "Ex.: Cor",
  "例如：红色": "Ex.: Vermelho",
  "可添加颜色、尺寸、口味等属性。": "Adicione atributos como cor, tamanho ou sabor.",
  "移除此未保存变体": "Remover variante não guardada",
  "下载变体模板": "Descarregar modelo de variantes",
  "导入变体": "Importar variantes",
  "请选择不超过 5MB 的 JPG、PNG 或 WebP 图片": "Escolha uma imagem JPG, PNG ou WebP até 5 MB",
  "请上传不超过 5MB 的 XLSX 文件": "Carregue um ficheiro XLSX até 5 MB",
  "表头不匹配，请使用变体模板": "Os cabeçalhos não correspondem. Utilize o modelo de variantes.",
  "请提供 1 至 100 条变体": "Introduza entre 1 e 100 variantes",
  "条码和商品编码必须使用文本格式": "Os códigos de barras e de produto devem estar em formato de texto",
  "售价须为有效金额，最多两位小数": "Introduza um preço válido com até duas casas decimais",
  "每个变体最多 12 个属性": "Até 12 atributos por variante",
  "请完整填写属性和属性值": "Preencha cada atributo e o respetivo valor",
  "同一变体不能重复填写属性": "Um atributo não pode aparecer duas vezes na mesma variante",
  "属性组合或规格重复": "Combinação de atributos ou especificação duplicada",
  "商品变体已变化，请重新打开编辑窗口": "As variantes foram alteradas. Volte a abrir o editor.",
  "变体不存在或重复": "Variante em falta ou duplicada",
  "变体数据格式不正确": "Dados da variante inválidos",
  "变体标识重复": "Identificador de variante duplicado",
  "扫描原小票，选择商品并填写原因。退款以现金退还。": "Leia o talão, selecione os artigos e indique o motivo. O reembolso é efetuado em numerário.",
  "扫描原小票二维码": "Ler código QR do talão",
  "扫描退货商品条码": "Ler código de barras do produto devolvido",
  "退货记录": "Registo de devoluções",
  "退货单号": "Número da devolução",
  "退货原因": "Motivo da devolução",
  "可退数量": "Quantidade disponível para devolução",
  "退货数量": "Quantidade a devolver",
  "现金退款": "Reembolso em numerário",
  "确认退货并记录现金退款": "Confirmar devolução e reembolso",
  "退货已完成": "Devolução concluída",
  "退货小票二维码": "Código QR do talão de devolução",
  "退货时请出示此码": "Apresente este código para devoluções",
  "请选择退货商品并填写原因": "Selecione artigos e indique um motivo",
  "核实原退货": "Verificar devolução anterior",
  "上次退货结果待确认，请重试原请求，勿重复退现金。": "A devolução anterior não está confirmada. Verifique novamente; não repita o reembolso em numerário.",
  "未找到唯一可退商品，请在列表选择": "Selecione o artigo na lista",
  "该分类已有商品，不能添加下级分类": "Esta categoria contém produtos e não pode ter subcategorias.",
  "收起菜单": "Recolher menu",
  "展开菜单": "Expandir menu",
  "收起": "Recolher",
  "展开": "Expandir",
  "全部分类": "Todas as categorias",
  "全部收起": "Recolher tudo",
  "全部展开": "Expandir tudo",
  "单机尊享版": "Versão local Premium",
  "连锁商户版": "Versão para cadeias",
  "用户与门店角色管理": "Utilizadores e funções por loja",
  "集中管理多家门店": "Gerir várias lojas centralmente",
  "按门店分配员工与角色": "Atribuir funcionários e funções por loja",
  "连接云端后，统一维护门店资料，并按权限切换和管理不同门店。": "Ligue-se à nuvem para gerir os dados das lojas centralmente e alternar entre lojas de acordo com as suas permissões.",
  "连接云端后，为用户分配多个门店及对应角色，管理各门店的操作权限。": "Ligue-se à nuvem para atribuir utilizadores a várias lojas com as respetivas funções e permissões.",
  "此功能需连接云端并使用有权限的账号。本机数据保留。": "Esta função requer uma ligação à nuvem e uma conta autorizada. Os dados locais são mantidos.",
  "预览示例": "Pré-visualização de exemplo",
  "修改即时预览，保存后生效。示例不生成订单。": "As alterações aparecem imediatamente; guarde para aplicar. Este exemplo não cria uma encomenda.",
  "小票设置": "Definições do talão",
  "小票设置已保存": "Definições do talão guardadas",
  "顶部字样": "Texto do cabeçalho",
  "底部字样": "Texto do rodapé",
  "支持多行文字，留空则不显示。保存后应用于本机小票预览和打印。": "Utilize várias linhas ou deixe em branco para ocultar. O texto guardado aparece na pré-visualização e impressão dos talões locais.",
  "当日订单流水已用完": "A sequência diária de encomendas foi esgotada",
  "订单编号格式不正确": "Formato do número de encomenda inválido",
  "订单编号重复，请核对后导入": "Números de encomenda duplicados. Verifique antes de importar.",
  "升级开通": "Upgrade",
  "累计消费": "Consumo acumulado",
  "优惠合计": "Desconto total",
  "会员流水": "Movimentos do membro",
  "备份包含会员规则、积分、余额及等级流水；恢复不会再次充值或扣款。": "As cópias de segurança incluem regras, pontos, saldo e histórico de níveis. O restauro não repete carregamentos nem cobranças.",
  "会员优惠已变化，请重新核算后确认": "Os benefícios do membro foram alterados. Recalcule antes de confirmar.",
  "等级方式": "Modo do nível",
  "手动指定": "Atribuído manualmente",
  "会员设置": "Definições de membros",
  "会员设置已保存": "Definições de membros guardadas",
  "积分规则": "Regras de pontos",
  "每消费 1 单位金额获得积分": "Pontos ganhos por unidade monetária gasta",
  "抵扣 1 单位金额所需积分": "Pontos necessários por unidade monetária descontada",
  "最高抵扣比例（%）": "Desconto máximo com pontos (%)",
  "消费积分按折扣及积分抵扣后的实付金额向下取整；充值不送积分。填 0 可关闭对应积分功能。": "Os pontos são arredondados por defeito a partir do valor pago após descontos e utilização de pontos. Os carregamentos não geram pontos. Introduza 0 para desativar a função correspondente.",
  "新增等级": "Adicionar nível",
  "等级名称": "Nome do nível",
  "累计消费门槛": "Limite de consumo acumulado",
  "实付比例（%）": "Percentagem do preço a pagar (%)",
  "按累计实付消费自动升级；首级门槛为 0。实付比例 100 表示原价，90 表示九折。规则仅影响后续结算。": "O nível aumenta com o consumo pago acumulado. O primeiro limite deve ser 0. Uma percentagem de 100 significa o preço completo; 90 significa 10% de desconto. As alterações aplicam-se a vendas futuras.",
  "移除": "Remover",
  "调整积分": "Ajustar pontos",
  "调整等级": "Alterar nível",
  "现金充值金额": "Valor do carregamento em numerário",
  "积分增减数量": "Ajuste de pontos",
  "自动等级": "Nível automático",
  "操作原因": "Motivo",
  "请确认已收到现金，确认后立即计入会员余额。": "Confirme a receção do numerário. O saldo do membro será creditado imediatamente.",
  "正数增加积分，负数扣减积分；不能扣成负数。": "Os valores positivos adicionam pontos; os negativos deduzem pontos. O saldo não pode ser inferior a zero.",
  "选择自动等级后，按累计消费门槛评定；手动指定的等级不自动升级。": "Os níveis automáticos utilizam limites de consumo acumulado. Os níveis manuais não são atualizados automaticamente.",
  "确认已收现金并充值": "Confirmar receção do numerário e carregar",
  "确认保存": "Confirmar e guardar",
  "等级流水": "Histórico de níveis",
  "抵扣积分": "Pontos utilizados",
  "获得积分": "Pontos ganhos",
  "本机余额": "Saldo local",
  "本机会员资产与流水保存在当前浏览器，请定期备份。": "Os saldos e movimentos dos membros locais são guardados neste navegador. Faça cópias de segurança regularmente.",
  "消费结算": "Pagamento de venda",
  "余额消费": "Pagamentos com saldo",
  "余额支付": "Pagar com saldo",
  "等级优惠": "Desconto do nível",
  "余额不足，请先充值或选择现金": "Saldo insuficiente. Carregue ou selecione numerário.",
  "订单和会员资产已保存在本机": "Encomenda e saldos dos membros guardados localmente",
  "现金实收含充值，余额消费不重复计入": "O numerário recebido inclui carregamentos; os pagamentos com saldo não são contabilizados novamente",
  "单机版 · 本机保存 · 支持现金、会员余额与积分": "Versão local · Guardado localmente · Numerário, saldos e pontos de membros",
  "商品分类、商品、会员、订单、会员规则与资产流水": "Categorias, produtos, membros, encomendas, regras de membros e movimentos de conta",
  "请填写有效名称或原因": "Introduza um nome ou motivo válido",
  "会员数值超出允许范围": "O valor do membro está fora do intervalo permitido",
  "积分必须为整数": "Os pontos devem ser um número inteiro",
  "请设置 1 至 20 个会员等级": "Defina entre 1 e 20 níveis de membro",
  "等级名称和门槛不能重复，首级门槛必须为 0": "Os nomes e limites dos níveis devem ser únicos; o primeiro limite deve ser 0",
  "不支持的会员操作": "Operação de membro não suportada",
  "相同请求的内容不一致": "O mesmo pedido contém dados diferentes",
  "请输入有效充值金额": "Introduza um valor de carregamento válido",
  "积分调整须为非零整数": "O ajuste de pontos deve ser um inteiro diferente de zero",
  "会员等级不存在": "Nível de membro não encontrado",
  "单机版支持现金或余额支付": "A versão local suporta numerário ou pagamentos com saldo",
  "会员余额不足或支付数据不正确": "Saldo do membro insuficiente ou dados de pagamento inválidos",
  "会员流水格式错误": "Formato do movimento de membro inválido",
  "会员流水引用不存在": "O movimento refere um membro inexistente",
  "会员流水与订单不一致": "O movimento do membro não corresponde à encomenda",
  "订单缺少会员流水": "Falta o movimento de membro desta encomenda",
  "已有会员使用此等级，不能删除": "Este nível é utilizado no histórico de membros e não pode ser removido",
  "会员资产币种不同，不能合并": "As moedas das contas dos membros são diferentes e não podem ser combinadas",
  "会员规则不同，请先核对规则再导入": "As regras de membros são diferentes. Verifique antes de importar.",
  "已有会员资产流水，不能更改本机币种": "Existe histórico de movimentos de membros. A moeda local não pode ser alterada.",
  "连接云端": "Ligar à nuvem",
  "云端地址": "Endereço da nuvem",
  "协议": "Protocolo",
  "支持 HTTP 和 HTTPS 地址。": "São suportados endereços HTTP e HTTPS.",
  "保存云端地址后，在 POS 界面登录。": "Guarde o endereço da nuvem e inicie sessão no POS.",
  "单机版不支持此功能，请连接云端": "Indisponível na versão local. Ligue-se à nuvem.",
  "演示订单会计入本机看板，适合体验和试用。": "As encomendas de demonstração aparecem no painel local e destinam-se a avaliação.",
  "以下是本机当前数据，清理前建议先导出备份。": "Dados locais atuais. Exporte uma cópia de segurança antes de limpar.",
  "包含 12 个末级分类；重复记录自动跳过，完成后显示本次新增数量。": "Inclui 12 categorias finais. Os registos existentes são ignorados; os números indicam os registos adicionados após a conclusão.",
  "加载进度": "Progresso do carregamento",
  "等待加载演示数据": "Pronto para carregar dados de demonstração",
  "正在写入本机数据…": "A guardar dados locais…",
  "待加载": "Por carregar",
  "本次新增": "Adicionados agora",
  "确认退出": "Terminar sessão",
  "是否确认退出？": "Tem a certeza de que pretende terminar sessão?",
  "退出登录": "Terminar sessão",
  "选择币种": "Selecionar moeda",
  "云端设置": "Definições da nuvem",
  "开始使用单机版": "Começar localmente",
  "本机还没有业务数据，选择一种方式开始。": "Este dispositivo não contém dados de negócio. Escolha como começar.",
  "体验示例商品、会员和现金订单": "Explore produtos, membros e encomendas de exemplo em numerário",
  "导入 Excel 商品或恢复 JSON 备份": "Importe produtos do Excel ou restaure uma cópia JSON",
  "Excel 商品导入": "Importar produtos do Excel",
  "恢复 JSON 备份": "Restaurar cópia JSON",
  "暂时跳过": "Ignorar por agora",
  "币种设置": "Definições de moeda",
  "币种": "Moeda",
  "搜索币种": "Pesquisar moedas",
  "输入币种代码或名称": "Código ou nome da moeda",
  "已选择": "Selecionado",
  "设置本机收银币种。": "Defina a moeda da caixa local.",
  "当前公司下所有门店统一使用此币种。": "Todas as lojas desta empresa partilham esta moeda.",
  "修改币种不会自动换算商品价格；历史订单保留原币种。": "Alterar a moeda não converte os preços dos produtos. As encomendas existentes mantêm a moeda original.",
  "请选择有效币种": "Selecione uma moeda válida",
  "币种设置已保存": "Definições de moeda guardadas",
  "仅管理员可以修改公司币种": "Apenas os administradores podem alterar a moeda da empresa",
  "币种已变化，请重新核对订单": "A moeda foi alterada. Verifique novamente a encomenda.",
  "历史订单币种不能修改": "A moeda de uma encomenda existente não pode ser alterada",
  "备份商品币种与当前币种不同，不能直接合并": "Os produtos da cópia utilizam outra moeda e não podem ser combinados diretamente",
  "当前扫码支付通道仅支持人民币，请使用现金": "O serviço atual de pagamento por leitura só suporta CNY. Utilize numerário.",
  "现有会员钱包和优惠券仅支持人民币": "As carteiras e cupões existentes dos membros apenas utilizam CNY",
  "金额须为有效金额，最多两位小数": "Introduza um valor válido com até duas casas decimais",
  "售价（{0}）*": "Preço ({0}) *",
  "售价（{0}）": "Preço ({0})",
  "成交单价（{0}）": "Preço unitário de venda ({0})",
  "金额（{0}）": "Valor ({0})",
  "优惠券面额（{0}）": "Valor do cupão ({0})",
  "请输入“{0}”以继续": "Escreva “{0}” para continuar",
  "加载演示数据": "Carregar dados de demonstração",
  "清理所有数据": "Limpar todos os dados locais",
  "演示数据已加载": "Dados de demonstração carregados",
  "演示数据包含分类、商品、会员和示例现金订单，会计入本机看板；重复加载不会覆盖现有记录。": "Os dados de demonstração incluem categorias, produtos, um membro e uma encomenda em numerário contabilizada no painel local. Recarregar mantém os registos existentes.",
  "将删除本机全部业务数据、挂单和购物车，保留语言、币种及后台地址。此操作不能撤销。": "Serão eliminados todos os dados de negócio locais, encomendas suspensas e carrinhos. O idioma, a moeda e o endereço de gestão são mantidos. Esta operação não pode ser anulada.",
  "先导出备份": "Exportar primeiro uma cópia de segurança",
  "请输入“确认清理”以继续": "Escreva “确认清理” para continuar",
  "确认清理": "Confirmar eliminação",
  "请输入确认清理": "Introduza o texto de confirmação",
  "业务数据翻译": "Traduções dos dados de negócio",
  "译文为空时显示原文；条码、编号和会员姓名不翻译。": "As traduções vazias utilizam o texto original. Os códigos de barras, códigos e nomes de membros não são traduzidos.",
  "编辑翻译": "Editar traduções",
  "翻译数据格式不正确": "Dados de tradução inválidos",
  "翻译字段或长度不正确": "Campo ou comprimento da tradução inválido",
  "不支持的翻译类型": "Tipo de tradução não suportado",
  "记录不存在": "Registo não encontrado",
  "仅单机版可操作": "Disponível apenas na versão local",
  "本机数据清理失败": "Não foi possível limpar os dados locais",
  "维护翻译需要店长或管理员权限": "Um responsável ou administrador deve editar as traduções",
  "记录不存在或不属于当前门店": "Registo não encontrado ou indisponível para esta loja",
  "翻译字段不正确": "Campo de tradução inválido",
  "翻译内容过长": "A tradução é demasiado longa",
  "请先在 Odoo 安装所选语言": "Instale primeiro o idioma selecionado no Odoo",
  "属性值": "Valor do atributo",
  "演示条码已被使用，未加载演示数据": "O código de barras de demonstração já está em uso. Nenhum dado de demonstração foi carregado.",
  "注册时间": "Data de registo",
  "资料更新时间": "Perfil atualizado",
  "等级评估开始": "Início da avaliação do nível",
  "等级评估结束": "Fim da avaliação do nível",
  "增加": "Aumento",
  "待核销": "A aguardar preparação",
  "禁用 {0}": "Desativar {0}",
  "删除第 {0} 行": "Eliminar linha {0}",
  "当前订单 · {0} 件": "Encomenda atual · {0} artigos",
  "数量：{0} 件": "Quantidade: {0}",
  "数量 {0}": "Quantidade {0}",
  "共 {0} 件商品": "{0} produtos",
  "共 {0} 条": "{0} registos",
  "{0} 条/页": "{0} linhas/página",
  "{0} 笔销售订单": "{0} encomendas de venda",
  "RO POS · 门店收银": "RO POS · Caixa da loja",
  "当前浏览器无法切换全屏，请使用浏览器的全屏菜单": "Utilize o menu de ecrã inteiro do navegador.",
  "本机订单仍保留：{0}": "Encomendas locais mantidas: {0}",
  "登录身份或门店权限已变化，请重新登录；离线现金记录仍保存在本机": "A conta ou o acesso à loja foi alterado. Inicie sessão novamente. Os registos locais de numerário permanecem neste dispositivo.",
  "门店收银": "Caixa da loja",
  "电商订单": "Encomendas online",
  "会员服务": "Serviços de membros",
  "离线模式：仅限本机缓存资料和门店现金收银": "Sem ligação: apenas dados em cache e pagamentos em numerário na loja",
  "切换门店会清空当前购物车。如需保留商品，请取消并先挂单。": "Mudar de loja limpa o carrinho. Para o manter, cancele e suspenda primeiro esta encomenda.",
  "订单核销和业绩看板需要连接后台": "Ligue-se à gestão para consultar a preparação e o desempenho.",
  "会员建档、充值和发券需要联网": "Ligue-se para criar membros, efetuar carregamentos ou emitir cupões.",
  "睿鸥门店收银系统": "Ruiou POS",
  "登录页导航": "Navegação de início de sessão",
  "RO POS 门店收银系统": "RO POS Caixa da loja",
  "睿鸥科技 版权所有": "© Ruiou Technology. Todos os direitos reservados.",
  "· 点击重新检测": "· Clique para verificar novamente",
  "上传离线订单，待上传 {0} 笔": "Enviar encomendas offline ({0} pendentes)",
  "离线订单上传进度": "Progresso do envio offline",
  "已处理": "Processados",
  "笔": "movimentos",
  "成功": "Com sucesso",
  "笔 · 失败": "movimentos · Falharam",
  "· 未处理": "· Pendentes",
  "已处理订单数": "Encomendas processadas",
  "待上传 {0} 笔订单，上传成功后自动移出队列。": "{0} encomendas pendentes. As encomendas enviadas saem automaticamente da fila.",
  "关闭窗口后，上传会继续进行。": "O envio continua após fechar esta janela.",
  "选择当前员工有权限的门店。各门店待同步记录独立保留。": "Selecione uma loja a que tenha acesso. Cada loja mantém os seus próprios registos pendentes.",
  "当前门店": "Loja atual",
  "离线收银 · 价格与库存为缓存数据 · 仅支持门店现金单 ·": "Caixa offline · Preços e stock em cache · Apenas numerário na loja ·",
  "缓存更新于": "Cache atualizada",
  "当前门店未准备离线商品": "Os produtos offline não estão disponíveis para esta loja.",
  "还没有可操作的门店": "Nenhuma loja disponível",
  "请管理员分配门店后重新连接。": "Peça a um administrador para atribuir uma loja e volte a ligar-se.",
  "重新连接": "Voltar a ligar",
  "当前离线，连接后台后可查看此页面。": "Está sem ligação. Ligue-se à gestão para ver esta página.",
  "单机版可备份、恢复本机分类、商品、会员与现金订单。在线版待上传订单请使用顶部上传入口。": "Faça cópias e restaure categorias, produtos, membros e encomendas locais em numerário. Para encomendas pendentes do modo online, utilize Enviar na barra superior.",
  "员工操作": "Ações do funcionário",
  "切换用户": "Mudar de utilizador",
  "返回登录": "Voltar ao início de sessão",
  "购物车还有商品，请先挂单，再返回登录。本机资料会保留。": "O carrinho contém artigos. Suspenda a encomenda antes de voltar ao início de sessão. Os dados locais serão mantidos.",
  "返回收银去挂单": "Voltar à caixa para suspender",
  "返回登录，保留当前员工的本机记录": "Voltar ao início de sessão e manter os registos locais deste funcionário",
  "锁定界面": "Bloquear ecrã",
  "单机版无账号密码，请使用系统锁屏": "A versão local não tem palavra-passe. Utilize o bloqueio de ecrã do dispositivo.",
  "保留当前工作，使用本人密码解锁": "Mantenha o trabalho e desbloqueie com a sua palavra-passe",
  "工作台已锁定": "Área de trabalho bloqueada",
  "· 当前订单已保留": "· Encomenda atual mantida",
  "员工密码": "Palavra-passe do funcionário",
  "输入当前员工密码": "Introduza a sua palavra-passe",
  "联网验证密码后即可解锁。": "Ligue-se para verificar a palavra-passe e desbloquear.",
  "正在验证…": "A verificar…",
  "解锁工作台": "Desbloquear área de trabalho",
  "添加收货地址": "Adicionar morada de entrega",
  "收货人 *": "Destinatário *",
  "手机号 *": "Telefone *",
  "省份 *": "Província *",
  "选择省份": "Selecionar província",
  "城市 *": "Cidade *",
  "选择城市": "Selecionar cidade",
  "区县 *": "Distrito *",
  "选择区县": "Selecionar distrito",
  "详细地址 *": "Morada *",
  "保存地址": "Guardar morada",
  "后台地址不正确": "Endereço de gestão inválido",
  "连接后将进入后台部署的完整睿鸥收银系统。": "Ligue-se para abrir o sistema Ruiou POS completo alojado na sua gestão.",
  "睿鸥后台地址": "Endereço da gestão Ruiou",
  "请填写完整站点地址。连接后页面会整体跳转，登录、接口、图片和支付都由该后台提供。": "Introduza o endereço completo. Será redirecionado para esse site, que fornece o início de sessão, serviços, imagens e pagamentos.",
  "清除已保存地址": "Limpar endereço guardado",
  "保存并进入睿鸥后台": "Guardar e ligar",
  "优惠券规则": "Regras de cupões",
  "面额 / 门槛": "Valor / Compra mínima",
  "草稿": "Rascunho",
  "已生效": "Ativo",
  "已失效": "Expirado",
  "规则已生效，优惠券可在发放页面领取": "Regra ativada. Os cupões estão disponíveis na página de emissão.",
  "返回列表": "Voltar à lista",
  "上次保存结果待确认，请核实原请求后再修改。": "Verifique a gravação anterior antes de efetuar mais alterações.",
  "核实 / 重试原保存": "Verificar / Repetir gravação",
  "优惠券搜索": "Pesquisar cupões",
  "优惠券名称": "Nome do cupão",
  "新建规则": "Nova regra",
  "创建普通固定面额规则，保存后确认启用。已生效规则只读；高级规则沿用后台配置。": "Crie uma regra de valor fixo, guarde e ative. As regras ativas são apenas de leitura; as regras avançadas são configuradas na gestão.",
  "资料与电商同步。": "Os dados são sincronizados com a loja online.",
  "发行 {0} 张 · 每人 {1} 张": "{0} emitidos · {1} por membro",
  "随机面额": "Valor variável",
  "充值": "Carregar",
  "查看详情": "Ver detalhes",
  "查看": "Ver",
  "编辑详情": "Editar detalhes",
  "卡号": "Número do cartão",
  "· 余额": "· Saldo",
  "。名称、分类及描述由同一商品的所有规格共用；售价仅修改当前规格。": ". O nome, a categoria e a descrição aplicam-se a todas as variantes; as alterações de preço aplicam-se apenas a esta variante.",
  "规则名称": "Nome da regra",
  "优惠券面额（元）": "Valor do cupão (CNY)",
  "随机面额规则，具体范围请在后台查看。": "Regra de valor variável. Consulte o intervalo de valores na gestão.",
  "使用门槛（0 为无门槛）": "Compra mínima (0 para nenhuma)",
  "发行数量": "Quantidade emitida",
  "每人限领": "Limite por membro",
  "有效期类型": "Tipo de validade",
  "领取后有效": "Válido após emissão",
  "固定起止时间": "Datas fixas",
  "领取后几天生效": "Dias até à ativação",
  "领取后几天到期": "Dias até à expiração",
  "生效时间": "Válido desde",
  "到期时间": "Expira em",
  "面额沿用现有整元券。时间按本机时区填写。新规则适用于全部商品、全部会员，仅通过发券入口发放。": "Os valores utilizam CNY inteiros. Introduza datas no fuso horário local. As novas regras aplicam-se a todos os produtos e membros, e os cupões são emitidos manualmente.",
  "此规则只读，避免影响现有优惠券。需调整时请新建规则。": "Esta regra é apenas de leitura para proteger os cupões existentes. Crie uma nova regra para efetuar alterações.",
  "确认启用已保存的规则后生成优惠券；当前表单未保存的修改不会生效。": "A ativação gera cupões a partir da regra guardada. As alterações não guardadas não serão aplicadas.",
  "确认启用已保存规则": "Ativar regra guardada",
  "单选商品分类穿梭框": "Seleção de categoria única",
  "逐级展开，选择最末级分类": "Expanda cada nível e selecione uma categoria final",
  "选入分类": "Adicionar categoria",
  "移除分类": "Remover categoria",
  "已选分类 ·": "Categoria selecionada ·",
  "选择后点击箭头移入": "Selecione uma categoria e clique na seta",
  "简体中文": "Chinês simplificado",
  "已导出 {0} 条记录": "{0} registos exportados",
  "导出失败：{0}": "Falha na exportação: {0}",
  "已选": "Selecionados",
  "条": "registos",
  "清空选择": "Limpar seleção",
  "Excel 导出需连接在线门店": "Ligue-se a uma loja online para exportar Excel",
  "仅导出勾选的记录，沿用当前排序": "Exportar registos selecionados pela ordem atual",
  "正在导出…": "A exportar…",
  "共": "Total",
  "条/页": "linhas/página",
  "第 {0} 页": "Página {0}",
  "选择第 {0} 行": "Selecionar linha {0}",
  "正在加载…": "A carregar…",
  "重新加载": "Recarregar",
  "无法读取会员操作记录": "Não foi possível carregar a atividade do membro",
  "会员已创建": "Membro criado",
  "会员已创建并选中": "Membro criado e selecionado",
  "已发放 {0} 张优惠券": "{0} cupões emitidos",
  "已发放 {0} {1}": "{0} {1} emitidos",
  "新建会员、充值和发券需联网。": "Ligue-se para criar membros, efetuar carregamentos ou emitir cupões.",
  "已有充值单，请继续处理": "Continuar a encomenda de carregamento existente",
  "上次操作结果待确认，请核实原请求": "Verificar o resultado do pedido anterior",
  "继续充值单": "Continuar carregamento",
  "核实 / 重试原操作": "Verificar / Repetir operação",
  "可用券": "Cupões disponíveis",
  "张": "cupões",
  "店长或电商管理员可发券。": "Os responsáveis de loja e administradores online podem emitir cupões.",
  "联系电话（选填）": "Telefone (opcional)",
  "自动生成会员卡号，创建后自动选中，购物车保留。": "É gerado um número de cartão e o membro é selecionado automaticamente. O carrinho é mantido.",
  "创建并选择会员": "Criar e selecionar membro",
  "赠送金额不收款，充值款全额到账后一起存入钱包。": "O bónus é gratuito e creditado com o carregamento após o pagamento integral.",
  "店长或管理员可设置赠送金额。": "Os responsáveis e administradores podem definir um bónus.",
  "合计到账": "Crédito total",
  "确认充值并收款": "Confirmar carregamento e pagar",
  "处理中…": "A processar…",
  "暂无可发放优惠券": "Nenhum cupão disponível para emissão",
  "满 {0} 可用": "Compra mínima {0}",
  "优惠券分页": "Paginação de cupões",
  "确认发放": "Confirmar emissão",
  "说明": "Descrição",
  "账户": "Conta",
  "申请时间": "Data do pedido",
  "申请原因": "Motivo do pedido",
  "审核状态": "Estado da avaliação",
  "处理意见": "Notas da avaliação",
  "券码": "Código do cupão",
  "面额": "Valor",
  "使用门槛": "Compra mínima",
  "订单号 / 支付流水号": "Referência de encomenda / pagamento",
  "搜索记录": "Pesquisar registos",
  "会员资料已保存": "Perfil do membro guardado",
  "返回会员列表": "Voltar aos membros",
  "正在加载会员资料…": "A carregar perfil do membro…",
  "上次资料保存结果待确认，请核实原请求。": "Verifique a gravação anterior do perfil.",
  "会员详情分类": "Separadores do membro",
  "会员基本资料": "Perfil do membro",
  "此处展示退换货申请与审核结果；审核通过不代表现金退款已经完成。": "As devoluções e os resultados da avaliação são apresentados aqui. A aprovação não significa que o reembolso em numerário foi concluído.",
  "编辑会员资料": "Editar perfil do membro",
  "会员姓名 *": "Nome do membro *",
  "邮箱": "E-mail",
  "会员等级": "Nível do membro",
  "卡号及等级在此只读；积分、余额由业务流水计算。": "O número do cartão e o nível são apenas de leitura. Os pontos e o saldo são calculados a partir dos movimentos.",
  "核实原保存": "Verificar gravação anterior",
  "RO-POS-单机备份-{0}.json": "RO-POS-copia-local-{0}.json",
  "已导出本机分类、商品、会员与历史现金订单": "Categorias, produtos, membros e encomendas em numerário locais exportados",
  "备份文件不能超过 100MB": "O ficheiro da cópia de segurança deve ter menos de 100 MB",
  "离线资料已合并保存；未覆盖原有数据，也未发起收款": "Dados locais combinados. Os dados existentes foram mantidos; nenhum pagamento foi iniciado.",
  "备份本机单机账本，包含商品分类、商品图片、会员资料、历史订单和现金收款。导入时保留原记录，相同记录自动跳过。": "Faça cópias de categorias, imagens de produtos, membros, encomendas e pagamentos em numerário. As importações mantêm os registos existentes e ignoram duplicados.",
  "现金订单": "Encomendas em numerário",
  "选择备份文件": "Escolher ficheiro de cópia de segurança",
  "导入预览": "Pré-visualização da importação",
  "新增分类": "Novas categorias",
  "个 · 商品": "· Produtos",
  "件 · 会员": "· Membros",
  "位 · 现金订单": "· Encomendas em numerário",
  "跳过相同记录": "Ignorar registos duplicados",
  "条。确认后只写入本机，不会再次收款。": "registos. A confirmação guarda localmente sem cobrar novamente.",
  "正在保存…": "A guardar…",
  "确认合并导入": "Combinar e importar",
  "数据保存在当前浏览器，请定期导出，清理浏览器数据会删除本机账本。": "Os dados são guardados neste navegador. Exporte regularmente: limpar os dados do navegador elimina o registo local.",
  "当前为在线版。此处导入的单机账本独立保存，不会直接覆盖云端商品、会员或订单。": "Modo online: os registos locais importados são guardados separadamente e não substituem produtos, membros ou encomendas da nuvem.",
  "升级在线版时，请保留此备份用于迁移。备份包含原始唯一标识、商品关联、交易时间、实收与找零，便于核对，避免重复入账。": "Mantenha esta cópia ao passar para o modo online. Contém identificadores originais, ligações a produtos, datas de transação, recebimentos e troco para reconciliação sem duplicados.",
  "收款时间 / 流水": "Hora do pagamento / Referência",
  "云端订单 {0}，金额 {1}，已收 {2}；可重试同步核对并确认本机记录。": "Encomenda na nuvem {0}: total {1}, pago {2}. Repita a sincronização para reconciliar o registo local.",
  "云端未找到该流水；可重试同步。": "Referência não encontrada na nuvem. Repita a sincronização.",
  "POS待同步记录-{0}-{1}.json": "POS-sincronizacao-pendente-{0}-{1}.json",
  "待同步订单": "Encomendas por sincronizar",
  "保留原收款流水核实与重试；同步成功后才移出列表。导出文件用于留存，不是单机账本导入文件。": "As referências de pagamento originais são mantidas para verificação e repetição até à sincronização. As exportações são para arquivo, não para importar registos locais.",
  "流水搜索": "Pesquisar movimentos",
  "时间、流水号、金额、失败原因": "Hora, referência, valor ou erro",
  "导出待同步记录": "Exportar registos pendentes",
  "待同步": "Sincronização pendente",
  "核实原单": "Verificar encomenda original",
  "重试同步": "Repetir sincronização",
  "会员钱包": "Carteira do membro",
  "待扫码提交": "A aguardar leitura",
  "结果待确认": "Resultado não confirmado",
  "撤销中": "A cancelar",
  "失败": "Falhou",
  "已撤销": "Anulado",
  "无法读取本机现金记录，请先核对云端订单": "Não é possível ler os registos locais de numerário. Verifique primeiro a encomenda na nuvem.",
  "请核对本次净收与现金实收金额": "Verifique o valor líquido e o numerário recebido",
  "云端尚未确认现金入账，本机记录继续保留": "O pagamento em numerário não está confirmado na nuvem. Os registos locais são mantidos.",
  "订单已付清": "Encomenda totalmente paga",
  "本笔现金已登记，可继续收取剩余金额": "Numerário registado. Pode receber o valor restante.",
  "提货核销成功": "Levantamento confirmado",
  "已查询原交易并处理撤销，请查看交易状态": "Transação original verificada e cancelamento processado. Verifique o estado.",
  "订单已取消": "Encomenda cancelada",
  "；本笔未入账，可修改后重试。": "; este pagamento não foi registado. Edite e tente novamente.",
  "；先刷新确认结果，或重试同一笔现金登记。": "; atualize para verificar ou repita o mesmo registo de numerário.",
  "原交易结果待确认，请先刷新订单核实": "Transação original não confirmada. Atualize a encomenda para verificar.",
  "付款码与所选支付方式不一致，请切换支付方式或重新扫码": "O código não corresponde ao método de pagamento. Mude de método ou leia novamente.",
  "请扫描顾客的微信或支付宝付款码": "Leia o código WeChat Pay ou Alipay do cliente",
  "本笔扫码金额须大于零，且不能超过剩余应收": "O pagamento deve ser superior a zero e não pode exceder o saldo em dívida",
  "已有支付待确认，请先查询原交易": "Existe um pagamento não confirmado. Verifique primeiro a transação original.",
  "付款码与当前待提交交易渠道不一致，请先撤销该笔": "O código não corresponde a esta transação pendente. Cancele-a primeiro.",
  "；请刷新订单确认原交易状态。": "; atualize a encomenda para verificar a transação original.",
  "改价记录": "Alterações de preço",
  "· 授权人": "· Autorizado por",
  "· 充值": "· Carregamento",
  "· 赠送": "· Bónus",
  "· 合计到账": "· Crédito total",
  "支付": "Pagamento",
  "，请先核实结果。": ". Verifique primeiro o resultado.",
  "刷新状态": "Atualizar estado",
  "核实并撤销扫码": "Verificar e anular pagamento por leitura",
  "顾客付款码": "Código de pagamento do cliente",
  "扫描顾客付款码": "Ler código de pagamento do cliente",
  "确认查询并撤销未完成的扫码交易？已确认成功的付款会保留。": "Verificar e cancelar pagamentos por leitura não concluídos? Os pagamentos confirmados serão mantidos.",
  "确认撤销": "Confirmar cancelamento",
  "正在确认…": "A confirmar…",
  "重试原收款": "Repetir pagamento original",
  "返回选购": "Voltar às compras",
  "收款成功后可打印小票。下方记录每笔已收金额。": "Imprima um talão após o pagamento. Os pagamentos individuais estão listados abaixo.",
  "会员充值收款": "Pagamento de carregamento do membro",
  "订单收款": "Pagamento da encomenda",
  "已收齐": "Totalmente pago",
  "部分收款": "Parcialmente pago",
  "订单应付": "Total da encomenda a pagar",
  "已收": "Recebido",
  "已充值 {0}，充值后余额 {1}": "Carregados {0}. Novo saldo: {1}",
  "全额收款确认后才增加会员钱包余额。": "O saldo da carteira aumenta após confirmação do pagamento integral.",
  "当前扫码交易": "Pagamento por leitura atual",
  "。确认结果或撤销成功前，不能重复收款或改收现金。": ". Não repita o pagamento nem mude para numerário antes de confirmar ou cancelar.",
  "此订单已通过小程序发起支付，请核实原支付结果；不能切换柜台收款。": "O pagamento foi iniciado no miniprograma. Verifique-o aí; o pagamento ao balcão está indisponível.",
  "核对并提货": "Verificar e receber",
  "取消订单": "Cancelar encomenda",
  "混合支付时，修改本次抵扣金额，收取余款时再切换支付方式。": "Para pagamentos parciais, introduza o valor deste pagamento e mude de método para o restante.",
  "本次抵扣订单金额": "Valor aplicado à encomenda",
  "应找零": "Troco a entregar",
  "本笔后剩余": "Restante após pagamento",
  "重试同一笔现金登记": "Repetir o mesmo registo de numerário",
  "扫描顾客付款码，确认本次收款金额。": "Leia o código do cliente e confirme o valor do pagamento.",
  "本次扫码金额": "Valor do pagamento por leitura",
  "请扫描微信 / 支付宝付款码": "Ler código WeChat Pay / Alipay",
  "确认商品已交付给顾客？": "Confirmar a entrega dos produtos ao cliente?",
  "先查询支付结果，再撤销未确认的扫码交易？": "Verificar os resultados dos pagamentos e cancelar os pagamentos por leitura não confirmados?",
  "确认取消未付款订单？": "Cancelar a encomenda não paga?",
  "已确认成功的交易保留；撤销可能退回刚扣取的扫码款。已收现金保留。": "Os pagamentos confirmados são mantidos. O cancelamento pode reembolsar pagamentos por leitura cobrados recentemente. O numerário já recebido é mantido.",
  "请至少选择一家门店": "Selecione pelo menos uma loja",
  "结束日期不能早于开始日期": "A data final não pode ser anterior à data inicial",
  "提货码 / 订单号": "Código de levantamento / Número de encomenda",
  "核对订单": "Verificar encomenda",
  "搜索列表": "Pesquisar na lista",
  "按所选门店和下单时间查询，核对订单和商品后确认提货。": "Filtre por loja e data da encomenda. Verifique a encomenda e os produtos antes de confirmar o levantamento.",
  "展示所选期间新建或收到款项的订单，支持查看和补打小票。": "Encomendas criadas ou pagas no período selecionado. Consulte detalhes ou reimprima talões.",
  "门店销售": "Venda em loja",
  "配送": "Entrega",
  "查看 / 打印": "Ver / Imprimir",
  "单据与小票": "Encomendas e talões",
  "门店编号": "Código da loja",
  "所属门店 / 角色": "Lojas / Funções",
  "请至少选择一家所属门店": "Atribua pelo menos uma loja",
  "门店新增": "Nova loja",
  "用户新增": "Novo utilizador",
  "门店搜索": "Pesquisar lojas",
  "用户搜索": "Pesquisar utilizadores",
  "名称、编号、地址": "Nome, código ou morada",
  "姓名、账号、所属门店": "Nome, conta ou loja",
  "用户": "Utilizador",
  "新增": "Adicionar",
  "门店名称": "Nome da loja",
  "姓名": "Nome",
  "联系电话": "Telefone",
  "允许店长／管理员改价": "Permitir alterações de preço por responsáveis / administradores",
  "获准的店长或管理员改价时必须填写原因，系统会保留原价和操作记录。": "Os responsáveis autorizados devem indicar um motivo para alterar preços. O preço original e a atividade são registados.",
  "营业时间": "Horário de funcionamento",
  "新门店归属当前账号的默认公司，并将你关联为店长。": "As novas lojas pertencem à empresa predefinida e têm-no como responsável.",
  "新密码（留空不修改）": "Nova palavra-passe (deixe em branco para manter)",
  "登录密码": "Palavra-passe de acesso",
  "所属门店与角色": "Lojas e funções atribuídas",
  "家": "lojas",
  "角色": "Função",
  "店员": "Funcionário",
  "店长": "Responsável",
  "同一账号可以加入多家门店，并为每家门店分别设置角色。取消勾选后将移除该门店权限。": "Uma conta pode ter funções diferentes em várias lojas. Desmarcar uma loja remove o acesso.",
  "姓名、账号和密码属于统一登录资料，修改会影响此账号的所有门店登录。": "O nome, a conta e a palavra-passe são partilhados por todas as lojas. As alterações afetam o acesso em todas elas.",
  "校验通过 · 将新建分类": "Válido · Será criada uma nova categoria",
  "待校验": "Validação pendente",
  "文件不能超过 5MB": "O ficheiro não pode exceder 5 MB",
  "请选择 JPG、PNG 或 WebP 图片": "Escolha uma imagem JPG, PNG ou WebP",
  "图片不能超过 2000 万像素": "A imagem não pode exceder 20 megapíxeis",
  "示例商品": "Produto de exemplo",
  "食品 / 休闲零食 / 坚果": "Alimentação / Snacks / Frutos secos",
  "500g / 袋": "500 g / saco",
  "可选": "Opcional",
  "RO-POS-单机商品导入模板.xlsx": "RO-POS-modelo-importacao-produtos.xlsx",
  "请上传 .xlsx 文件": "Carregar ficheiro .xlsx",
  "Excel 中没有可导入的数据": "A folha de cálculo não contém dados importáveis",
  "表头必须包含商品名称、分类和售价": "Os cabeçalhos devem incluir nome do produto, categoria e preço",
  "每次最多导入 500 行商品": "Importe até 500 linhas de cada vez",
  "已创建 {0} 件商品": "{0} produtos criados",
  "上次": "Anterior",
  "件商品的提交结果待确认，请核实原提交，避免重复创建。": "produtos aguardam confirmação. Verifique o envio anterior para evitar duplicados.",
  "使用模板中的完整分类名称；每批最多 500 行，上传后直接进入预览校验。": "Utilize os caminhos completos de categoria do modelo. Até 500 linhas por lote; os carregamentos seguem diretamente para validação.",
  "商品名称 *": "Nome do produto *",
  "售价（元）*": "Preço (CNY) *",
  "行通过 ·": "linhas válidas ·",
  "行错误": "linhas inválidas",
  "商品校验预览": "Pré-visualização da validação de produtos",
  "{0} 第 {1} 行": "{0}, linha {1}",
  "件商品": "produtos",
  "图片暂不可用": "Imagem indisponível",
  "暂无图片": "Sem imagem",
  "空白行": "Linha vazia",
  "请复制表头下方的商品数据": "Copie os dados de produtos abaixo dos cabeçalhos",
  "粘贴后超过 500 行，请分批录入": "Mais de 500 linhas. Cole em lotes menores.",
  "粘贴内容超出右侧列边界，请从更靠左的单元格粘贴": "Os dados ultrapassam a última coluna. Cole a partir de uma célula mais à esquerda.",
  "商品编辑表格": "Folha de produtos",
  "选中格子直接粘贴，Tab 横移，Enter 下移": "Selecione uma célula para colar. Tab avança para a direita; Enter avança para baixo.",
  "新增行": "Adicionar linha",
  "删除第": "Eliminar linha",
  "行": "linha",
  "空白行不提交；分类填写完整路径；条码保留前导零。每批最多 500 行。": "As linhas vazias são ignoradas. Introduza caminhos completos de categoria. Os zeros iniciais dos códigos de barras são preservados. Até 500 linhas por lote.",
  "已打开浏览器打印窗口，请在窗口中确认打印结果": "Janela de impressão aberta. Confirme o resultado nessa janela.",
  "小票宽度": "Largura do talão",
  "浏览器打印时选择同宽纸张，关闭页眉页脚。": "Selecione a largura de papel correspondente e desative os cabeçalhos e rodapés ao imprimir.",
  "已取消 · 非收款凭证": "Cancelado · Não é comprovativo de pagamento",
  "待付款订单 · 非收款凭证": "Encomenda não paga · Não é comprovativo de pagamento",
  "时间": "Data e hora",
  "收银": "Operador de caixa",
  "方式": "Método",
  "已核销提货": "Levantamento efetuado",
  "请妥善保管小票 · 感谢惠顾": "Guarde o talão · Obrigado",
  "请先联网准备当前门店离线商品": "Ligue-se para preparar os produtos offline desta loja",
  "离线仅支持门店现金单，请取消优惠券、积分及附加服务": "O modo offline suporta apenas numerário. Remova cupões, pontos e serviços adicionais.",
  "商品缓存不完整，请联网更新离线数据": "A cache de produtos está incompleta. Ligue-se para a atualizar.",
  "未找到会员，请核对会员码或手机号": "Membro não encontrado. Verifique o código ou o telefone.",
  "订单正在结算，请完成后重新扫描": "Pagamento em curso. Termine antes de efetuar outra leitura.",
  "未找到商品": "Produto não encontrado",
  "未找到会员，请核对会员码、卡号或手机号": "Membro não encontrado. Verifique o código, o cartão ou o telefone.",
  "找到多位会员，请核对后选择": "Foram encontrados vários membros. Verifique e selecione um.",
  "浏览器存储不可用，挂单未保存，请勿关闭当前购物车": "Armazenamento do navegador indisponível. A encomenda não foi suspensa. Mantenha este carrinho aberto.",
  "最多保留 20 笔挂单，请先处理已有挂单": "Até 20 encomendas suspensas. Processe primeiro as existentes.",
  "已挂单，保存在当前设备及员工门店下": "Encomenda suspensa neste dispositivo para o funcionário e a loja atuais",
  "取回这笔挂单将替换当前购物车。如需保留商品，请取消并先挂单。": "Retomar substitui o carrinho. Para o manter, cancele e suspenda primeiro a encomenda atual.",
  "已取回挂单，商品价格和库存将在结算时重新核算": "Encomenda retomada. Os preços e o stock serão verificados no pagamento.",
  "删除后无法取回这笔挂单，确认删除？": "Esta encomenda suspensa não poderá ser recuperada após a eliminação. Eliminar?",
  "原订单待核实，请联网后继续原订单": "A encomenda original necessita de verificação. Ligue-se para a continuar.",
  "请重新核算": "Recalcule antes de continuar",
  "请输入有效现金实收，不能低于应收金额（最多两位小数）": "Introduza o numerário recebido, igual ou superior ao valor a pagar, com até duas casas decimais",
  "单机-": "Local-",
  "离线-": "Offline-",
  "现金已收": "Numerário recebido",
  "现金已收 · 待同步": "Numerário recebido · Sincronização pendente",
  "现金单已保存在本机，可在业绩看板查看并导出备份。": "Encomenda em numerário guardada localmente. Consulte-a no painel e exporte uma cópia de segurança.",
  "现金单已保存在本机，云端确认入账后自动清理本地记录。": "Encomenda em numerário guardada localmente. O registo local é removido após confirmação na nuvem.",
  "订单结果待确认，购物车已保留，请联网后继续原订单": "Resultado da encomenda não confirmado. Carrinho mantido. Ligue-se para continuar a encomenda original.",
  "已切换离线现金收银：会员优惠暂停；附加服务请移除后结算": "Mudou para pagamento offline em numerário. Os descontos de membro estão suspensos; remova serviços adicionais antes de pagar.",
  "请等待扫码完成": "Aguarde a conclusão da leitura",
  "当前门店仅允许获准的店长或管理员改价": "Apenas responsáveis ou administradores autorizados podem alterar preços",
  "请输入 0 至 1000000 元、最多两位小数的成交单价": "Introduza um preço unitário entre 0 e 1 000 000 CNY, com até duas casas decimais",
  "清空当前订单": "Limpar encomenda atual",
  "将移除当前购物车中的全部商品，确认清空？": "Remover todos os produtos do carrinho?",
  "充值记录保存失败，请从订单列表核对": "Não foi possível guardar o carregamento. Verifique em Encomendas.",
  "订单已取消，但本机记录保存失败，请勿关闭页面": "Encomenda cancelada, mas a gravação local falhou. Mantenha esta página aberta.",
  "已返回收银台，购物车已保留": "Regressou à caixa. Carrinho mantido.",
  "请联网后核实原订单，购物车已保留": "Ligue-se para verificar a encomenda original. Carrinho mantido.",
  "请先核实当前订单的支付结果": "Verifique primeiro o resultado do pagamento desta encomenda",
  "订单尚未取消，请核实当前状态": "A encomenda não foi cancelada. Verifique o estado.",
  "取消未完成，请重试或核实原订单：": "Cancelamento incompleto. Repita ou verifique a encomenda original:",
  "当前订单 ·": "Encomenda atual ·",
  "件": "artigos",
  "购物车已保留 ·": "Carrinho mantido ·",
  "订单结果待确认": "Resultado da encomenda não confirmado",
  "，请继续原订单或取消未付款订单。": ". Continue a encomenda original ou cancele a encomenda não paga.",
  "继续原订单": "Continuar encomenda original",
  "选择": "Selecionar",
  "数量：": "Quantidade:",
  "当前订单会员": "Membro da encomenda atual",
  "更换": "Alterar",
  "全部商品分类": "Todas as categorias de produtos",
  "正在处理": "A processar",
  "次扫码…": "leituras…",
  "正在加载商品…": "A carregar produtos…",
  "二级分类": "Subcategorias",
  "查看商品": "Ver produtos",
  "{0} 件商品": "{0} produtos",
  "添加": "Adicionar",
  "已售罄": "Esgotado",
  "加载中…": "A carregar…",
  "确认会员": "Confirmar membro",
  "关闭会员确认": "Fechar confirmação do membro",
  "会员码 / 手机号": "Código de membro / Telefone",
  "待确认会员": "Membro a confirmar",
  "未填写": "Não indicado",
  "确认会员后，将关联到当前购物车。": "Confirme para associar este membro ao carrinho atual.",
  "确认使用该会员": "Utilizar este membro",
  "结算与打印": "Pagamento e impressão",
  "小票": "Talão",
  "收款界面": "Ecrã de pagamento",
  "正在准备收款，请稍候…": "A preparar pagamento. Aguarde…",
  "原订单结果待确认，请继续原订单，避免重复开单。": "A encomenda original não está confirmada. Continue-a para evitar duplicados.",
  "核实原订单": "Verificar encomenda original",
  "扫描会员码 / 输入手机号": "Ler código de membro / Introduzir telefone",
  "扫描会员码，或输入会员码、手机号": "Leia ou introduza o código de membro ou telefone",
  "当前会员": "Membro atual",
  "本单优惠": "Descontos da encomenda",
  "离线会员信息来自本机缓存，积分、优惠券暂不可用。": "Os dados offline do membro estão em cache. Os pontos e cupões estão indisponíveis.",
  "未获取": "Indisponível",
  "不使用优惠券": "Sem cupão",
  "正在核算优惠…": "A calcular descontos…",
  "扫码后自动显示会员、积分和可用优惠券": "Leia o código para consultar o membro, pontos e cupões disponíveis",
  "也可输入手机号，按回车查询": "Ou introduza um telefone e prima Enter",
  "应付": "Valor a pagar",
  "关闭移除确认": "Fechar confirmação de remoção",
  "商品改价": "Alterar preço do produto",
  "关闭改价": "Fechar alteração de preço",
  "原单价": "Preço unitário original",
  "当前小计": "Subtotal atual",
  "成交单价（元）": "Preço unitário de venda (CNY)",
  "改价原因": "Motivo da alteração de preço",
  "确认改价": "Confirmar alteração de preço",
  "识别会员": "Procurar membro",
  "扫描 / 输入名称、会员码、卡号、手机号": "Leia / Introduza nome, código de membro, cartão ou telefone",
  "识别": "Procurar",
  "当前余额": "Saldo atual",
  "更换会员": "Alterar membro",
  "此处办理会员业务，当前销售购物车保持不变。": "Gira os serviços do membro aqui. O carrinho de venda é mantido.",
  "挂单仅保存在当前设备，取回后重新核算价格与库存。": "As encomendas suspensas são guardadas apenas neste dispositivo. Os preços e o stock são verificados ao retomar.",
  "暂无挂单": "Nenhuma encomenda suspensa",
  "种商品": "tipos de produto",
  "取回": "Retomar",
  "保存备注": "Guardar notas",
  "支持 F2–F4、F6–F9、Enter 或 Ctrl+Alt+字母。": "Utilize F2–F4, F6–F9, Enter ou Ctrl+Alt+letra.",
  "点击按键框后按下快捷键。设置仅用于当前员工在此浏览器的收银操作。": "Clique num campo de tecla e prima um atalho. Estas definições aplicam-se apenas ao funcionário atual neste navegador.",
  "支持 F2–F4、F6–F9、Enter、Ctrl+Alt+字母。部分键盘需同时按 Fn。输入框和弹窗内暂停快捷操作，扫码收款仍需确认。": "Utilize F2–F4, F6–F9, Enter ou Ctrl+Alt+letra. Alguns teclados requerem também Fn. Os atalhos são suspensos em campos de texto e janelas. Os pagamentos por leitura continuam a exigir confirmação.",
  "未启用": "Não ativado",
  "禁用": "Desativar",
  "快捷键重复，请更换按键或禁用其中一项。": "Atalhos duplicados. Altere uma tecla ou desative uma ação.",
  "恢复默认": "Restaurar predefinições",
  "保存设置": "Guardar definições",
  "分类已更新": "Categoria atualizada",
  "分类已创建": "Categoria criada",
  "该分类包含商品或下级分类，不能删除": "Não é possível eliminar uma categoria com produtos ou subcategorias",
  "删除商品分类": "Eliminar categoria de produto",
  "确认删除分类“{0}”？": "Eliminar a categoria “{0}”?",
  "分类已删除": "Categoria eliminada",
  "包含下级": "Tem subcategorias",
  "暂无分类": "Sem categorias",
  "编辑分类": "Editar categoria",
  "分类名称 *": "Nome da categoria *",
  "无（一级分类）": "Nenhuma (categoria principal)",
  "选择上级后会移动整个分类；不能移动到自身或下级。": "Selecionar uma categoria superior move toda a categoria. Não é possível movê-la para si própria nem para uma descendente.",
  "请选择": "Selecione uma opção",
  "请选择门店": "Selecione uma loja",
  "全部门店（{0}）": "Todas as lojas ({0})",
  "已选 1 家": "1 loja selecionada",
  "已选 {0} 家门店": "{0} lojas selecionadas",
  "门店筛选：{0}": "Filtro de lojas: {0}",
  "全选": "Selecionar tudo",
  "暂无可管理门店": "Nenhuma loja disponível para gerir",
  "正在加载业绩数据…": "A carregar dados de desempenho…",
  "笔销售订单": "encomendas de venda",
  "不含赠送金额": "Exclui bónus",
  "退款数据暂不可统计": "Dados de reembolso indisponíveis",
  "每日收款": "Recebimentos diários",
  "金额趋势": "Evolução do valor",
  "所选日期每小时收款趋势": "Recebimentos por hora da data selecionada",
  "所选期间每日收款趋势": "Recebimentos diários do período selecionado",
  "金额（元）": "Valor (CNY)",
  "时段": "Período",
  "单日": "Dia",
  "峰值": "Pico",
  "所选期间各收款方式金额占比饼图": "Distribuição dos métodos de pagamento no período selecionado",
  "／ 找零": "/ Troco",
  "统计所选门店和日期区间内已确认的收款，不含本机待同步记录；实收尚未扣除退款。分次付款按期间到账金额计入。销售收款客单价为期间商品销售收款除以对应销售订单数，不含会员充值。后台暂无可核对的退款金额与完成时间数据，退款和净收暂不可统计。": "Recebimentos confirmados nas lojas e datas selecionadas, excluindo registos locais por sincronizar e antes de reembolsos. Os pagamentos parciais são contabilizados quando recebidos. O valor médio é o recebimento de produtos dividido pelas encomendas de venda, excluindo carregamentos. Os totais e datas de reembolso estão indisponíveis, pelo que ainda não é possível calcular reembolsos e recebimentos líquidos.",
  "请求超时，结果待确认，请先核实原单据": "O pedido excedeu o tempo limite. Verifique a transação original antes de repetir.",
  "已切换到单机版": "Mudou para a versão local",
  "本机缓存写入失败，相关资料离线不可用": "Falha ao gravar a cache. Estes dados não estão disponíveis offline.",
  "请输入完整的睿鸥后台地址，例如 https://pos.example.com": "Introduza o endereço completo da gestão Ruiou, por exemplo https://pos.example.com",
  "后台地址不能包含账号、密码、查询参数或锚点": "O endereço não pode conter credenciais, parâmetros de consulta ou fragmentos",
  "正式环境必须使用 HTTPS；本机或局域网调试可使用 HTTP": "Utilize HTTPS em produção. HTTP é permitido para testes locais.",
  "离线页面缓存注册失败：需要 HTTPS 或 localhost": "Falha ao registar a cache offline: é necessário HTTPS ou localhost",
  "本机存储不可用，请勿离线收款": "Armazenamento local indisponível. Não receba pagamentos offline.",
  "保存失败，请勿关闭页面或重复收款": "Falha ao guardar. Mantenha a página aberta e não cobre novamente.",
  "本机保存失败，请勿重复收款": "Falha na gravação local. Não cobre novamente.",
  "请先联网登录并选择门店": "Ligue-se, inicie sessão e selecione primeiro uma loja",
  "请先联网登录并缓存门店资料，再使用离线收银": "Inicie sessão online e guarde os dados da loja em cache antes de utilizar a caixa offline",
  "当前门店尚未准备离线商品": "Os produtos offline não estão disponíveis para esta loja",
  "当前门店尚未完成自动缓存，请联网后稍候再试": "A cache da loja está incompleta. Ligue-se e tente novamente em breve.",
  "请输入至少两位会员卡号或姓名；离线仅可查询已缓存会员": "Introduza pelo menos dois caracteres do cartão ou nome. Apenas os membros em cache podem ser pesquisados offline.",
  "该会员没有已缓存地址，请联网维护": "Este membro não tem morada em cache. Ligue-se para gerir moradas.",
  "此功能需要连接后台，离线仅支持缓存商品、自提现金单与挂单": "Ligue-se para utilizar esta função. O modo offline suporta produtos em cache, encomendas em numerário para levantamento e encomendas suspensas.",
  "离线准备需要 HTTPS 或 localhost": "A configuração offline requer HTTPS ou localhost",
  "离线页面缓存尚未就绪，请刷新后重试": "A cache da página offline não está pronta. Atualize e tente novamente.",
  "连接或门店已变化，请重新准备离线数据": "A ligação ou a loja foi alterada. Prepare novamente os dados offline.",
  "离线订单未保存，请勿清空购物车或重复收款": "A encomenda offline não foi guardada. Não limpe o carrinho nem cobre novamente.",
  "无法保存同步结果，下次将安全重试": "Não foi possível guardar o resultado da sincronização. Será efetuada uma repetição segura.",
  "请由原收银员登录原门店后同步": "O operador original deve iniciar sessão na loja original para sincronizar",
  "云端未确认完整收款，本机记录继续保留": "O pagamento integral não está confirmado na nuvem. Os registos locais são mantidos.",
  "同步失败，请重试": "A sincronização falhou. Tente novamente.",
  "粘贴内容过大，请分批录入": "O conteúdo colado é demasiado grande. Utilize lotes menores.",
  "单元格引号不完整，请重新复制": "Aspas de célula incompletas. Copie novamente os dados.",
  "每批最多粘贴 500 行数据": "Cole até 500 linhas por lote",
  "分类完整名称": "Caminho completo da categoria",
  "每批请输入 1 至 500 行": "Introduza entre 1 e 500 linhas por lote",
  "第 {0} 行超过 7 列，请按指定顺序复制": "A linha {0} excede 7 colunas. Copie pela ordem indicada.",
  "进入收款": "Abrir pagamento",
  "扫码收款": "Pagamento por leitura",
  "请为每项操作设置不同的有效按键": "Atribua uma tecla válida diferente a cada ação",
  "浏览器无法保存设置，请检查是否允许本地存储": "Não é possível guardar as definições. Verifique as permissões de armazenamento do navegador.",
  "数据文本格式或长度不正确": "Formato ou comprimento do texto inválido",
  "数据标识不正确": "Identificador de dados inválido",
  "金额须为有效人民币金额，最多两位小数": "Introduza um valor CNY válido com até duas casas decimais",
  "单机收银员": "Operador local",
  "商品分类层级存在循环": "A hierarquia de categorias contém um ciclo",
  "请选择商品分类或填写完整分类路径": "Selecione uma categoria ou introduza o caminho completo",
  "商品分类最多 8 级，每级不超过 80 个字符": "As categorias suportam até 8 níveis, com 80 caracteres por nível",
  "请选择末级商品分类，或填写完整分类路径": "Selecione uma categoria final ou introduza o caminho completo",
  "只能选择最末级商品分类": "Apenas podem ser selecionadas categorias finais",
  "商品图片格式不正确": "Formato da imagem do produto inválido",
  "商品名称不能为空": "O nome do produto é obrigatório",
  "商品已不存在，请重新选择": "O produto já não existe. Selecione outro.",
  "商品数量不正确": "Quantidade de produto inválida",
  "商品合计有变化，请重新结算": "O total dos produtos foi alterado. Volte a efetuar o pagamento.",
  "现金实收不能小于应收": "O numerário recebido não pode ser inferior ao valor a pagar",
  "会员不存在，请重新选择": "O membro não existe. Selecione novamente.",
  "相同订单号的内容不一致，不能再次登记": "Este número de encomenda tem dados diferentes e não pode ser registado novamente",
  "分类不存在": "A categoria não existe",
  "分类名称不能为空": "O nome da categoria é obrigatório",
  "上级分类不存在": "A categoria superior não existe",
  "不能把分类移动到自身或下级分类": "Não é possível mover uma categoria para si própria ou para descendentes",
  "同一上级下已有同名分类": "Já existe uma categoria com este nome nesta categoria superior",
  "该分类包含下级分类，不能删除": "Não é possível eliminar uma categoria com subcategorias",
  "该分类已有商品，不能删除": "Não é possível eliminar uma categoria com produtos",
  "至少保留一个商品分类": "Mantenha pelo menos uma categoria de produtos",
  "请检查会员姓名和手机号": "Verifique o nome e o telefone do membro",
  "手机号已被其他会员使用": "O telefone é utilizado por outro membro",
  "商品不存在": "O produto não existe",
  "商品条码或编码重复": "Código de barras ou de produto duplicado",
  "请至少填写一行商品": "Introduza pelo menos uma linha de produto",
  "每次最多导入 {0} 行商品": "Importe até {0} linhas de produtos de cada vez",
  "请检查会员姓名和电话": "Verifique o nome e o telefone do membro",
  "该手机号已存在，请搜索会员": "O telefone já existe. Pesquise o membro.",
  "每次只能创建 1 至 {0} 件商品": "Crie entre 1 e {0} produtos de cada vez",
  "第 {0} 行商品条码或编码重复": "Código de barras ou de produto duplicado na linha {0}",
  "找不到本机订单": "Encomenda local não encontrada",
  "单机版不支持此功能，请连接睿鸥后台": "Indisponível na versão local. Ligue-se à gestão Ruiou.",
  "不是受支持的 RO POS 单机备份": "Cópia local RO POS não suportada",
  "备份集合格式错误或超过 50000 条": "Coleção inválida na cópia ou mais de 50 000 registos",
  "分类名称为空": "Nome da categoria vazio",
  "分类上级引用不存在": "Referência da categoria superior não encontrada",
  "备份缺少商品分类": "Faltam categorias de produtos na cópia",
  "会员姓名为空": "Nome do membro vazio",
  "备份包含重复标识": "A cópia contém identificadores duplicados",
  "订单明细格式错误": "Formato da linha de encomenda inválido",
  "订单商品引用或数量错误": "Referência de produto ou quantidade inválida na encomenda",
  "订单日期不正确": "Data de encomenda inválida",
  "订单会员引用不存在": "Referência de membro da encomenda não encontrada",
  "订单合计或收款金额不一致": "O total da encomenda ou o valor pago não corresponde",
  "同一标识内容冲突，请核对后重新导入": "Dados em conflito para o mesmo identificador. Verifique e importe novamente.",
  "商品条码或编码重复，不能自动合并": "Um código de barras ou de produto duplicado impede a combinação automática",
  "会员手机号重复，不能自动合并": "Um telefone de membro duplicado impede a combinação automática",
  "首页": "Início",
  "公司介绍": "Empresa",
  "产品展示": "Produtos",
  "关于我们": "Sobre nós",
  "界面语言": "Idioma da interface",
  "搜索": "Pesquisar",
  "商品搜索": "Pesquisar produtos",
  "会员搜索": "Pesquisar membros",
  "订单搜索": "Pesquisar encomendas",
  "商品名称、条码、编码": "Nome do produto, código de barras ou código",
  "姓名、卡号、手机号": "Nome, número de cartão ou telefone",
  "订单号 / 会员姓名 / 手机号": "Número de encomenda / membro / telefone",
  "登录账号": "Iniciar sessão",
  "员工账号": "Conta de funcionário",
  "请输入员工账号": "Introduza a conta de funcionário",
  "密码": "Palavra-passe",
  "请输入密码": "Introduza a palavra-passe",
  "显示密码": "Mostrar palavra-passe",
  "隐藏密码": "Ocultar palavra-passe",
  "登录工作台": "Iniciar sessão",
  "正在登录…": "A iniciar sessão…",
  "正在检查登录状态…": "A verificar sessão…",
  "RO POS 门店收银系统，与电商订单协同管理。": "RO POS, caixa de loja com encomendas online integradas.",
  "一个工作台，连接门店日常": "Uma área de trabalho para as operações diárias da loja",
  "从选购开单到收款提货，让门店操作更集中。": "Da seleção de produtos ao pagamento e levantamento, todas as operações da loja ficam reunidas.",
  "商品扫码与挂单": "Leitura de códigos de barras e encomendas suspensas",
  "会员建档、充值与发券": "Dados de membros, carregamentos e cupões",
  "现金、微信及支付宝收款": "Numerário, WeChat Pay e Alipay",
  "提货核销与小票打印": "Confirmação de levantamentos e impressão de talões",
  "关于 RO POS": "Sobre o RO POS",
  "面向零售门店的收银工作台，由睿鸥科技提供。": "Uma área de trabalho para caixas de lojas de retalho, da Ruiou Technology.",
  "员工使用已分配门店权限的账号登录": "Os funcionários iniciam sessão com o acesso à loja atribuído",
  "订单与电商业务统一管理": "Gestão unificada de encomendas de loja e online",
  "支持浏览器打印小票": "Impressão de talões pelo navegador",
  "单机版 · 无需登录": "Versão local · Sem início de sessão",
  "连接睿鸥后台": "Ligar à gestão Ruiou",
  "进入已保存的睿鸥后台": "Abrir gestão Ruiou guardada",
  "睿鸥科技": "Ruiou Technology",
  "版权所有": "Todos os direitos reservados",
  "系统工具条": "Barra de ferramentas do sistema",
  "工作台": "Área de trabalho",
  "门店工作台": "Área de trabalho da loja",
  "返回收银": "Voltar à caixa",
  "本机时间": "Hora local",
  "全屏": "Ecrã inteiro",
  "退出全屏": "Sair do ecrã inteiro",
  "在线": "Online",
  "离线": "Offline",
  "连接中": "A ligar",
  "单机版": "Versão local",
  "本机单机模式": "Modo local independente",
  "后台在线": "Gestão online",
  "后台离线": "Gestão offline",
  "正在连接": "A ligar",
  "选择门店": "Selecionar loja",
  "切换门店": "Mudar de loja",
  "确认切换": "Confirmar mudança",
  "门店": "Loja",
  "全部门店": "Todas as lojas",
  "本机门店": "Loja local",
  "选择商品": "Selecionar produtos",
  "当前订单": "Encomenda atual",
  "搜索商品": "Pesquisar produtos",
  "搜索商品名称 / 条码，或直接扫码": "Pesquise por nome ou código de barras, ou efetue a leitura",
  "扫描商品条码或搜索": "Leia o código de barras ou pesquise",
  "全部商品": "Todos os produtos",
  "本机商品": "Produtos locais",
  "查看更多": "Mais",
  "收起分类": "Recolher categorias",
  "商品分类": "Categorias de produtos",
  "没有找到商品": "Nenhum produto encontrado",
  "试试其他名称、条码或分类": "Experimente outro nome, código de barras ou categoria",
  "商品已售罄": "Sem stock",
  "标准规格": "Padrão",
  "订单汇总": "Resumo da encomenda",
  "输入模式": "Modo de introdução",
  "商品数量键盘": "Teclado de quantidades",
  "增加数量": "Aumentar quantidade",
  "减少数量": "Diminuir quantidade",
  "退格": "Apagar último carácter",
  "移除所选商品": "Remover produto selecionado",
  "商品": "Produto",
  "单价": "Preço unitário",
  "数量": "Quantidade",
  "小计": "Subtotal",
  "金额": "Valor",
  "清空": "Limpar",
  "清空订单": "Limpar encomenda",
  "挂单": "Suspender",
  "取单": "Retomar",
  "改价": "Alterar preço",
  "结算": "Pagamento",
  "会员结算": "Pagamento de membro",
  "继续购物": "Continuar compras",
  "开始一笔新订单": "Iniciar nova encomenda",
  "选择商品，或直接扫描商品条码": "Selecione um produto ou leia o código de barras",
  "购物车为空": "O carrinho está vazio",
  "移除商品": "Remover produto",
  "是否移除此商品？": "Remover este produto?",
  "确认移除": "Remover",
  "取消": "Cancelar",
  "确认": "Confirmar",
  "关闭": "Fechar",
  "返回": "Voltar",
  "完成": "Concluir",
  "保存": "Guardar",
  "修改": "Editar",
  "删除": "Eliminar",
  "重试": "Tentar novamente",
  "刷新": "Atualizar",
  "查询": "Pesquisar",
  "重置": "Repor",
  "会员": "Membro",
  "散客": "Cliente ocasional",
  "选择会员": "Selecionar membro",
  "查询会员": "Procurar membro",
  "扫描会员码或输入手机号": "Leia o código de membro ou introduza o telefone",
  "请扫描会员码": "Ler código de membro",
  "会员管理": "Membros",
  "会员新建": "Novo membro",
  "新建会员": "Novo membro",
  "创建会员": "Criar membro",
  "会员详情": "Dados do membro",
  "会员资料": "Perfil do membro",
  "基本资料": "Perfil",
  "会员姓名": "Nome do membro",
  "会员卡号": "Número do cartão",
  "手机号": "Telefone",
  "等级": "Nível",
  "积分": "Pontos",
  "余额": "Saldo",
  "可用积分": "Pontos disponíveis",
  "账户余额": "Saldo da conta",
  "可用优惠券": "Cupões disponíveis",
  "编辑资料": "Editar perfil",
  "保存资料": "Guardar perfil",
  "取消关联会员": "Desassociar membro",
  "会员充值": "Carregamento de membro",
  "发放优惠券": "Emitir cupão",
  "优惠券": "Cupões",
  "优惠券管理": "Cupões",
  "优惠券发放": "Emitir cupões",
  "优惠券名称 / 券码": "Nome / código do cupão",
  "无门槛": "Sem mínimo",
  "有效期至": "Válido até",
  "使用积分抵扣": "Utilizar pontos",
  "暂无适用于本单的优惠券": "Nenhum cupão disponível para esta encomenda",
  "收款": "Pagamento",
  "现金": "Numerário",
  "微信": "WeChat Pay",
  "支付宝": "Alipay",
  "现金收款": "Pagamento em numerário",
  "微信支付": "WeChat Pay",
  "支付方式": "Método de pagamento",
  "待支付金额": "Valor a pagar",
  "收款金额": "Valor recebido",
  "找零": "Troco",
  "确认收款": "Confirmar pagamento",
  "正在确认支付…": "A confirmar pagamento…",
  "核算中…": "A calcular…",
  "去收款": "Pagar",
  "收款成功": "Pagamento concluído",
  "打印小票": "Imprimir talão",
  "完成，下一单": "Concluir, próxima encomenda",
  "订单管理": "Encomendas",
  "订单核销": "Preparação de encomendas",
  "订单详情": "Detalhes da encomenda",
  "订单号": "Número de encomenda",
  "订单 / 会员": "Encomenda / Membro",
  "下单时间": "Data da encomenda",
  "订单状态": "Estado da encomenda",
  "订单金额": "Valor da encomenda",
  "全部": "Todos",
  "待付款": "Pagamento pendente",
  "待履约": "Preparação pendente",
  "已完成": "Concluído",
  "已关闭": "Fechado",
  "待收款": "Pagamento pendente",
  "待提货": "Pronto para levantamento",
  "已核销": "Entregue",
  "已取消": "Cancelado",
  "原订单": "Encomenda original",
  "查看原订单": "Ver encomenda original",
  "返回单据列表": "Voltar às encomendas",
  "导出 Excel": "Exportar Excel",
  "请先勾选需要导出的记录": "Selecione registos para exportar",
  "业绩看板": "Painel de desempenho",
  "经营概览": "Visão geral",
  "开始日期": "Data inicial",
  "结束日期": "Data final",
  "刷新数据": "Atualizar dados",
  "期间实收": "Recebimentos líquidos",
  "收款订单": "Encomendas pagas",
  "销售收款客单价": "Valor médio de venda",
  "退款金额": "Reembolsos",
  "商品销售收款": "Vendas de produtos",
  "会员充值实收": "Carregamentos de membros",
  "扣退款后净收": "Líquido após reembolsos",
  "分时收款": "Recebimentos ao longo do tempo",
  "收款方式": "Métodos de pagamento",
  "暂无收款": "Sem recebimentos",
  "本机现金销售": "Vendas locais em numerário",
  "含会员充值": "Inclui carregamentos de membros",
  "已完成退款": "Reembolsos concluídos",
  "暂不可统计": "Indisponível",
  "管理功能导航": "Navegação de gestão",
  "管理工作区": "Área de gestão",
  "已打开的页面": "Páginas abertas",
  "统计口径": "Critérios do relatório",
  "占期间实收": "Quota dos recebimentos",
  "时段峰值": "Período de pico",
  "单": "encomendas",
  "业务管理": "Negócio",
  "本机资料": "Dados locais",
  "本机设置": "Definições locais",
  "系统管理": "Sistema",
  "商品管理": "Produtos",
  "商品新建": "Novo produto",
  "新建商品": "Novo produto",
  "用户管理": "Utilizadores",
  "门店管理": "Lojas",
  "数据管理": "Dados",
  "系统设置": "Definições do sistema",
  "快捷键设置": "Atalhos de teclado",
  "新增用户": "Novo utilizador",
  "新增门店": "Nova loja",
  "名称": "Nome",
  "状态": "Estado",
  "操作": "Ações",
  "序号": "N.º",
  "类型": "Tipo",
  "描述": "Descrição",
  "行号": "Linha",
  "规格": "Variante",
  "条码": "Código de barras",
  "商品编码": "Código do produto",
  "售价": "Preço",
  "售价（元）": "Preço (CNY)",
  "备注": "Notas",
  "维护本机资料。": "Gerir dados locais.",
  "分类": "Categoria",
  "全选当前页": "Selecionar página atual",
  "关闭商品管理": "Fechar gestão de produtos",
  "关闭会员管理": "Fechar gestão de membros",
  "关闭订单管理": "Fechar gestão de encomendas",
  "上一页": "Anterior",
  "下一页": "Seguinte",
  "每页条数": "Linhas por página",
  "跳转页码": "Ir para a página",
  "前往": "Ir para",
  "页": "Página",
  "数据列表": "Tabela de dados",
  "暂无匹配记录，请调整搜索条件。": "Nenhum registo correspondente. Ajuste os filtros.",
  "列表分页": "Paginação da tabela",
  "跳转": "Ir",
  "商品新建步骤": "Passos de criação de produto",
  "选择方式": "Escolher método",
  "选择分类": "Escolher categoria",
  "填写数据": "Introduzir dados",
  "预览校验": "Validar",
  "手动新建": "Criar manualmente",
  "Excel 导入": "Importação Excel",
  "Excel 粘贴录入": "Colar do Excel",
  "上一步": "Anterior",
  "下一步": "Seguinte",
  "校验结果": "Resultados da validação",
  "校验通过": "Válido",
  "商品可编辑网格": "Grelha de produtos editável",
  "导入数据": "Importar dados",
  "导出数据": "Exportar dados",
  "分类搜索": "Pesquisar categorias",
  "分类名称或完整路径": "Nome da categoria ou caminho completo",
  "新建分类": "Nova categoria",
  "完整路径": "Caminho completo",
  "商品数": "Produtos",
  "末级": "Final",
  "编辑": "Editar",
  "分类名称": "Nome da categoria",
  "上级分类": "Categoria superior",
  "无上级分类": "Sem categoria superior",
  "维护本机多级分类；商品只能选择最末级分类。": "Gira os níveis das categorias locais; os produtos só podem utilizar categorias finais.",
  "订单上传": "Envio de encomendas",
  "上传离线订单": "Enviar encomendas offline",
  "正在上传离线订单": "A enviar encomendas offline",
  "上传未完成": "Envio incompleto",
  "本次上传结束": "Envio concluído",
  "暂无待上传订单": "Nenhuma encomenda para enviar",
  "查看待上传订单": "Ver encomendas pendentes",
  "后台上传": "Continuar em segundo plano",
  "本机没有待上传订单。": "Nenhuma encomenda pendente neste dispositivo.",
  "系统设置已保存": "Definições guardadas",
  "快捷键设置已保存": "Atalhos guardados",
  "操作未完成，请重试": "Operação não concluída. Tente novamente.",
  "操作失败": "A operação falhou",
  "查询中…": "A pesquisar…",
  "保存中…": "A guardar…",
  "更新中…": "A atualizar…",
  "识别中…": "A ler…",
  "文件读取失败": "Não foi possível ler o ficheiro",
  "查询已取消": "Pesquisa cancelada",
  "查询超时，请重试": "A pesquisa excedeu o tempo limite. Tente novamente.",
  "单机版 · 本机保存 · 支持现金收银与会员建档": "Versão local · Guardado localmente · Numerário e dados de membros",
  "本机单机账本": "Registo local",
  "单机账本": "Registo local",
  "数据范围": "Âmbito dos dados",
  "内容": "Conteúdo",
  "格式": "Formato",
  "商品分类、商品、会员、历史现金订单": "Categorias, produtos, membros e encomendas em numerário",
  "正在准备工作台": "A preparar área de trabalho",
  "门店资料与本机订单加载中": "A carregar dados da loja e encomendas locais",
  "正在切换用户": "A mudar de utilizador",
  "现金实收": "Numerário recebido",
  "现金净收": "Numerário líquido",
  "积分流水": "Histórico de pontos",
  "余额 / 充值流水": "Histórico de saldo / carregamentos",
  "订单记录": "Encomendas",
  "支付记录": "Pagamentos",
  "退货 / 售后": "Devoluções / Pós-venda",
  "支付时间": "Data do pagamento",
  "发生时间": "Data e hora",
  "变动类型": "Tipo de alteração",
  "流水说明": "Descrição",
  "交易流水号": "Identificador da transação",
  "分笔付款记录": "Pagamentos parciais",
  "充值金额": "Valor do carregamento",
  "赠送金额": "Valor do bónus",
  "钱包到账": "Carteira creditada",
  "钱包余额": "Saldo da carteira",
  "待入账": "Crédito pendente",
  "实付": "Pago",
  "商品小计": "Subtotal de produtos",
  "订单备注": "Notas da encomenda",
  "填写本次交易备注": "Adicione uma nota a esta transação",
  "支付待确认": "Pagamento por confirmar",
  "剩余应收": "Saldo em dívida",
  "已付金额": "Valor pago",
  "交易类型 / 核销": "Transação / Entrega",
  "状态 / 原因": "Estado / Motivo",
  "退单": "Devolução",
  "退单原因": "Motivo da devolução",
  "扫描小票二维码": "Ler código QR do talão",
  "关联原订单": "Encomenda original",
  "原订单号 / 商品 / 退货原因": "Encomenda original / Produto / Motivo",
  "地址": "Morada",
  "到店自提": "Levantamento em loja",
  "送货上门": "Entrega",
  "提货二维码": "Código QR de levantamento",
  "请凭此码提货": "Apresente este código para levantamento",
  "核对并核销": "Verificar e entregar",
  "商品名称": "Nome do produto",
  "商品描述": "Descrição do produto",
  "商品导入": "Importação de produtos",
  "上传 .xlsx 文件": "Carregar ficheiro .xlsx",
  "粘贴 Excel 数据": "Colar dados do Excel",
  "可扫描商品条码": "Código de barras legível do produto",
  "例如：500g / 袋": "Exemplo: 500 g / saco",
  "选择商品录入方式": "Escolha como adicionar produtos",
  "选择分类，填写单件商品资料": "Escolha uma categoria e introduza um produto",
  "上传模板文件，批量预览校验": "Carregue um modelo para validação em lote",
  "Excel 粘贴": "Colar do Excel",
  "复制表格内容，直接预览校验": "Cole células da folha de cálculo e valide",
  "创建一件单规格商品，先选择一个末级商品分类。": "Crie um produto de variante única. Comece por uma categoria final.",
  "下载导入模板": "Descarregar modelo de importação",
  "上传 Excel": "Carregar Excel",
  "选择商品分类": "Escolher categoria de produto",
  "填写商品资料": "Introduzir dados do produto",
  "分类：": "Categoria:",
  "商品图片": "Imagem do produto",
  "待上传商品图片": "Imagem do produto a carregar",
  "移除图片": "Remover imagem",
  "重新校验": "Validar novamente",
  "数据已修改，请重新校验": "Os dados foram alterados. Valide novamente.",
  "确认创建": "Criar",
  "下一步：校验": "Seguinte: Validar",
  "确认原提交结果": "Confirmar envio anterior",
  "当前离线，请联网后维护商品。": "Está sem ligação. Ligue-se para gerir produtos.",
  "图片最大 5MB；商品创建后上架，采用无库存下单。": "Imagens até 5 MB. Os produtos são publicados após a criação.",
  "核对资料后确认创建；如需修改，请返回上一步。": "Verifique os dados e crie. Volte atrás para editar.",
  "可直接修改表格；修改后需重新校验，全部通过后才能创建。": "Edite as células diretamente e valide novamente antes de criar.",
  "普通会员": "Membro padrão",
  "本机会员": "Membro local",
  "自动生成会员卡号。": "O número do cartão é gerado automaticamente.",
  "未填写手机号": "Sem número de telefone",
  "未留电话": "Sem telefone",
  "关闭提示": "Fechar mensagem",
  "关闭确认": "Fechar confirmação",
  "关闭结算": "Fechar pagamento",
  "关闭编辑": "Fechar editor",
  "关闭面板": "Fechar painel",
  "关闭系统设置": "Fechar definições",
  "关闭上传窗口": "Fechar carregamento",
  "关闭门店切换": "Fechar mudança de loja",
  "保存成功": "Guardado",
  "确认删除": "Confirmar eliminação",
  "确认取回": "Confirmar retoma",
  "删除挂单": "Eliminar encomenda suspensa",
  "取回挂单": "Retomar encomenda suspensa",
  "未选择会员": "Nenhum membro selecionado",
  "找不到会员": "Membro não encontrado",
  "会员不存在": "O membro não existe",
  "无法读取挂单记录": "Não foi possível carregar as encomendas suspensas",
  "无法恢复上次购物车": "Não foi possível restaurar o carrinho anterior",
  "无法读取离线订单记录": "Não foi possível carregar as encomendas offline",
  "购物车自动保存失败，请勿关闭页面": "A gravação automática do carrinho falhou. Mantenha esta página aberta.",
  "连接失败，请检查网络；已提交的操作请先核实结果": "A ligação falhou. Verifique a rede e confirme as operações enviadas.",
  "后台响应异常，请稍后重试；已提交的操作请先核实结果": "Resposta do servidor inválida. Tente mais tarde e verifique as operações enviadas.",
  "后台服务异常，请稍后重试；已提交的操作请先核实结果": "Servidor indisponível. Tente mais tarde e verifique as operações enviadas.",
  "请等待扫码完成后结算": "Aguarde o fim da leitura antes do pagamento",
  "请等待扫码完成后挂单": "Aguarde o fim da leitura antes de suspender a encomenda",
  "请等待扫码完成后清空": "Aguarde o fim da leitura antes de limpar",
  "扫码处理中，请稍候再结算": "Leitura em curso. Aguarde antes do pagamento.",
  "商品库存不足，未加购": "Stock insuficiente. Produto não adicionado.",
  "已达到当前库存数量": "Atingiu o limite de stock atual",
  "条码对应多个商品，请手动选择": "Vários produtos utilizam este código de barras. Selecione um manualmente.",
  "找到相关商品，请核对并手动选择": "Foram encontrados produtos relacionados. Verifique e selecione um.",
  "请输入改价原因，最多 200 字": "Introduza um motivo para a alteração de preço, até 200 caracteres",
  "请填写改价原因": "Introduza o motivo da alteração de preço",
  "结算核算失败，请稍后重试": "O cálculo do pagamento falhou. Tente novamente.",
  "购物车商品已变化，请重新核对": "Os artigos do carrinho foram alterados. Verifique novamente.",
  "产品介绍": "Produtos",
  "选择适合门店的版本": "Escolha a sua versão",
  "本机独立使用，或连接云端统一管理。": "Trabalhe localmente ou ligue-se à nuvem para gestão centralizada.",
  "商品与订单保存在本机，支持现金收款和本地数据备份。": "Produtos e encomendas guardados localmente, com pagamentos em numerário e cópias de segurança.",
  "无需登录，即可独立使用。": "Utilize de forma independente, sem iniciar sessão.",
  "保留本机数据管理，可开通微信、支付宝扫码收款。": "Mantenha a gestão local de dados e ative pagamentos WeChat e Alipay.",
  "联系升级购买；开通商户支付并配置参数后使用，扫码收款需联网。": "Contacte-nos para fazer o upgrade. Ative e configure os pagamentos do comerciante; a leitura requer internet.",
  "云端版本": "Versão na nuvem",
  "连接云端 Odoo，统一管理店铺、店员、商品、会员与订单。": "Ligue-se ao Odoo para gerir lojas, funcionários, produtos, membros e encomendas centralmente.",
  "在 POS 登录云端账号，按门店权限使用。": "Inicie sessão com a sua conta na nuvem e permissões de loja.",
  "账户登录": "ACESSO À CONTA",
  "支付设置": "Definições de pagamento",
  "员工管理": "Funcionários",
  "退货": "Devolução",
  "设置向导": "Assistente de configuração",
  "单机版设置步骤": "Passos de configuração local",
  "选择数据": "Escolher dados",
  "准备商品": "Preparar produtos",
  "完成设置": "Concluir configuração",
  "确认收银币种": "Confirmar moeda da caixa",
  "先设置收银币种，再准备商品数据。": "Defina a moeda e prepare os dados dos produtos.",
  "已有商品或订单，保留原币种。": "Existem produtos ou encomendas: mantenha a moeda original.",
  "已有商品或订单，请保留原币种": "Mantenha a moeda original dos produtos ou encomendas existentes.",
  "关联云端": "Ligar à nuvem",
  "先确认你的数据来源": "Escolha a origem dos dados",
  "使用已有资料，或为这台设备准备商品数据。": "Utilize dados existentes ou prepare produtos para este dispositivo.",
  "使用本机数据": "Utilizar dados locais",
  "导入商品": "Importar produtos",
  "Excel 导入、粘贴或手动录入": "Importe Excel, cole ou introduza manualmente",
  "读取备份资料和币种": "Ler dados e moeda da cópia",
  "准备商品数据": "Preparar dados dos produtos",
  "演示数据包含商品、会员和示例订单，会计入本机看板。": "Os produtos, membros e encomendas de demonstração serão incluídos no painel local.",
  "新增商品": "Novos produtos",
  "相同记录不会重复导入": "Os registos idênticos são ignorados",
  "已有数据不会重复创建。": "Os dados existentes não serão duplicados.",
  "一切就绪": "Tudo pronto",
  "正在处理，请稍候…": "A processar, aguarde…",
  "开始使用": "Começar",
  "确认加载数据": "Carregar dados",
  "预计记录": "Registos previstos",
  "未完成": "Incompleto",
  "等待处理": "Em espera",
  "准备就绪": "Pronto",
  "加载未完成，请重试": "Carregamento incompleto. Tente novamente.",
  "正在完成数据准备…": "A preparar dados…",
  "重复记录自动跳过，完成后显示本次新增数量。": "Os duplicados são ignorados. O número de novos registos aparece após a conclusão.",
  "备份必须包含有效商品": "A cópia deve conter produtos válidos.",
  "请先准备至少一件有效商品，再开始收银": "Adicione pelo menos um produto válido antes de utilizar a caixa.",
  "请选择数据来源": "Escolha uma origem de dados.",
  "请选择备份文件": "Escolha um ficheiro de cópia de segurança.",
  "请返回第二步重新选择备份文件": "Volte ao passo 2 e selecione novamente a cópia.",
  "备份币种与所选币种不一致，请返回确认": "A moeda da cópia é diferente. Volte atrás para confirmar.",
  "备份币种为 {0}，请返回第一步确认币种后再导入": "A moeda da cópia é {0}. Confirme-a no passo 1 antes de importar.",
  "管理会员资料与资产": "Gerir membros e saldos",
  "维护会员资料，查看会员等级、积分、余额与消费记录。": "Gira dados de membros, níveis, pontos, saldos e compras.",
  "设置会员等级与积分规则": "Definir níveis e pontos de membros",
  "配置会员等级、消费积分和积分抵扣规则。": "Configure níveis, pontos de compra e regras de utilização.",
  "开通微信与支付宝扫码收款": "Ativar pagamentos WeChat e Alipay",
  "配置商户支付参数，使用微信、支付宝扫码收款。扫码收款需要联网。": "Configure os pagamentos do comerciante para WeChat e Alipay. É necessária internet.",
  "连接云端管理业务": "Gerir o negócio na nuvem",
  "配置云端地址，在 POS 登录云端账号，按门店权限使用业务功能。": "Defina o endereço da nuvem e inicie sessão com as permissões da loja.",
  "未开通功能预览": "Pré-visualização da função",
  "当前版本尚未开通，升级后可使用。": "Faça o upgrade para desbloquear esta função.",
  "联系升级购买": "Contactar para upgrade",
  "单机-{0}": "Local-{0}",
  "演示会员 {0}": "Cliente de demonstração {0}",
  "调整列宽：{0}": "Ajustar largura da coluna: {0}",
  "应用 ID（AppID）": "ID da aplicação (AppID)",
  "商户号（MchID）": "ID do comerciante (MchID)",
  "API 密钥": "Chave API",
  "商户证书": "Certificado do comerciante",
  "商户私钥": "Chave privada do comerciante",
  "商户账号": "Conta do comerciante",
  "应用私钥": "Chave privada da aplicação",
  "支付宝公钥": "Chave pública Alipay",
  "单机版暂不开放微信、支付宝扫码收款。请联系睿鸥科技升级购买后开通。": "Contacte a Ruiou Technology para fazer o upgrade e ativar WeChat e Alipay.",
  "现金收款可正常使用。": "Os pagamentos em numerário estão disponíveis.",
  "启用扫码收款": "Ativar pagamentos por leitura",
  "升级开通后配置": "Configurar após o upgrade",
  "当前版本不可填写或保存支付参数。": "Os parâmetros de pagamento não podem ser editados nesta versão.",
  "请先完成门店、店员和商品设置": "Conclua primeiro a configuração da loja, funcionários e produtos.",
  "扫描原小票条码 / 输入订单号": "Leia o talão original / Introduza o número de encomenda",
  "商品条码": "Código de barras do produto",
  "购买数量": "Quantidade comprada",
  "此条码无法生成一维码": "Não é possível gerar este código de barras",
  "暂无条码": "Sem código de barras",
  "确认退款": "Confirmar reembolso",
  "翻译": "Traduções",
  "请先选择或创建门店": "Selecione ou crie primeiro uma loja.",
  "请先为此门店设置有效店员": "Atribua primeiro funcionários válidos a esta loja.",
  "请先准备可销售商品": "Adicione primeiro produtos disponíveis.",
  "联机版设置步骤": "Passos de configuração da nuvem",
  "确认店铺": "Confirmar loja",
  "店员设置": "Configuração de funcionários",
  "商品数据": "Dados dos produtos",
  "确认云端店铺": "Confirmar loja na nuvem",
  "已登录": "Sessão iniciada",
  "选择已有店铺，或创建一家新店。": "Selecione uma loja existente ou crie uma nova.",
  "店铺": "Loja",
  "请选择店铺": "Selecione uma loja",
  "创建或管理店铺": "Criar ou gerir lojas",
  "需要新增或修改店铺，请联系管理员。": "Contacte um administrador para adicionar ou editar lojas.",
  "确认店员与权限": "Confirmar funcionários e permissões",
  "此门店尚无有效店员。": "Esta loja não tem funcionários ativos.",
  "设置店员": "Configurar funcionários",
  "已有店员可直接确认；需要调整账号或权限，请联系管理员。": "Confirme os funcionários existentes; contacte um administrador para alterar contas ou permissões.",
  "确认商品数据": "Confirmar dados dos produtos",
  "先创建商品分类": "Criar primeiro categorias de produtos",
  "创建分类": "Criar categoria",
  "请管理员先准备商品分类，然后刷新检查。": "Peça a um administrador para criar categorias e atualize.",
  "导入或创建商品": "Importar ou criar produtos",
  "请联系店长或管理员准备商品，然后刷新检查。": "Peça ao responsável ou administrador para adicionar produtos e atualize.",
  "设置完成": "Configuração concluída",
  "开始使用前会再次检查云端资料。": "Os dados da nuvem serão verificados novamente antes de começar.",
  "正在检查云端数据…": "A verificar dados da nuvem…",
  "切换账号": "Mudar de conta",
  "刷新检查": "Atualizar e verificar",
  "确认并继续": "Confirmar e continuar",
  "保存云端地址后，使用云端账号登录。": "Guarde o endereço da nuvem e inicie sessão com a sua conta na nuvem.",
  "返回币种设置": "Voltar às definições de moeda",
  "保存并继续": "Guardar e continuar",
  "登录后继续配置云端店铺、店员和商品。本机数据保留。": "Após iniciar sessão, configure lojas, funcionários e produtos. Os dados locais são mantidos.",
  "修改地址": "Editar endereço",
  "登录并继续设置": "Iniciar sessão e continuar configuração",
  "已退款": "Reembolsado",
  "云端已有 {0} 件可销售商品": "{0} produtos disponíveis na nuvem",
  "此订单号无法生成条形码": "Não existe código de barras para este número de encomenda",
  "订单条形码：{0}": "Código de barras da encomenda: {0}"
};

const demoCopy: Record<string,string> = {
  "经典咖啡": "Café clássico",
  "纯牛奶": "Leite gordo",
  "黄油饼干": "Bolachas de manteiga",
  "演示商品": "Produtos de demonstração",
  "食品饮料": "Alimentos e bebidas",
  "日用清洁": "Limpeza diária",
  "米面粮油": "Cereais e óleos",
  "零食饮料": "Snacks e bebidas",
  "生鲜果蔬": "Fruta e legumes frescos",
  "乳品冷藏": "Laticínios refrigerados",
  "调味干货": "Temperos e produtos secos",
  "日用百货": "Artigos do dia a dia",
  "家庭清洁": "Limpeza doméstica",
  "酒水茶饮": "Vinhos e chás",
  "母婴用品": "Artigos para bebés",
  "宠物生活": "Artigos para animais",
  "咖啡茶饮": "Café e chá",
  "乳品": "Laticínios",
  "饼干零食": "Bolachas e snacks",
  "洗衣用品": "Lavandaria",
  "厨房清洁": "Limpeza da cozinha",
  "家居清洁": "Limpeza da casa",
  "洗发护发": "Cuidados do cabelo",
  "沐浴用品": "Artigos de banho",
  "口腔护理": "Higiene oral",
  "纸品": "Artigos de papel",
  "厨房用品": "Utensílios de cozinha",
  "文具": "Papelaria",
  "大米杂粮": "Arroz e cereais",
  "新鲜水果": "Fruta fresca",
  "调味酱料": "Molhos",
  "婴儿护理": "Cuidados do bebé",
  "宠物食品": "Alimentação para animais",
  "瓶装饮料": "Bebidas engarrafadas",
  "香醇咖啡": "Café aromático",
  "鲜牛奶": "Leite fresco",
  "燕麦饼干": "Bolachas de aveia",
  "洗衣液": "Detergente de roupa",
  "洗洁精": "Detergente da loiça",
  "地板清洁剂": "Detergente de chão",
  "洗发水": "Champô",
  "沐浴露": "Gel de banho",
  "牙膏": "Pasta de dentes",
  "抽纸": "Lenços de papel",
  "保鲜袋": "Sacos para alimentos",
  "笔记本": "Caderno",
  "精选大米": "Arroz selecionado",
  "新鲜苹果": "Maçãs frescas",
  "酿造酱油": "Molho de soja",
  "婴儿湿巾": "Toalhitas para bebé",
  "成猫粮": "Alimento para gatos adultos",
  "气泡水": "Água com gás",
  "250克": "250 g",
  "1升": "1 L",
  "200克": "200 g",
  "单件": "1 unidade"
};
export function portugueseDemo(value:string): string | undefined {
  if(demoCopy[value])return demoCopy[value];
  const match=value.match(/^(.*?) (\d+)$/);
  return match&&demoCopy[match[1]] ? `${demoCopy[match[1]]} ${match[2]}` : undefined;
}
